### ISSUE TITLE
结果与box会不会取错位呢？

### ISSUE THREAD

**Issue by llooper-dev** [hiroi-sora/PaddleOCR-json#1]
if (strget != "" && score != 0 && count != 0) { // 确定识别内容存在 
}else{
当识别的内容不存在的时候，这里没有对应的空值设置 ，在返回结果那你的boxs取了i。是不是会造成的错位，返回来的box不是对应的
}
可以加个QQ397720544吗，我也在用这paddleocr，有些东西要请教下？

**Comment by hiroi-sora** [comment]
非常感谢你的提议！看了一下确实存在这个问题，是我的疏忽。新版本中已经修复了这个漏洞。


我很菜的，只是配个环境然后改改官方demo这个样子，没有钻研过paddle的核心算法。大概没法给你什么有用的建议😂
