### ISSUE TITLE
我的项目也用到了 opencv, 可否将 opencv 路径也支持配置呢，这样的话，就不用引入 2 个 opencv 进去了

### ISSUE THREAD

**Issue by Riant** [hiroi-sora/PaddleOCR-json#103]
甚至如果可以支持在运行时传递这个路径参数应该会更方便
如题，感谢作者。

**Comment by hiroi-sora** [comment]
你好。在`PaddleOCR-json`的源码中，是没有指定dll搜索路径的。dll可能是在各个引用库的代码中进行加载。这样的话，不太方便传参配置。

不过，你可以反过来，让你的项目使用 `PaddleOCR-json` 目录中的 `opencv_world470.dll` 。或者，直接将你的程序文件，放置在 `PaddleOCR-json` 目录中。
