### ISSUE TITLE
c++菜鸡请教一个代码问题

### ISSUE THREAD

**Issue by KyleWang-Hunter** [hiroi-sora/PaddleOCR-json#104]
![2024-04-26_171232](https://github.com/hiroi-sora/PaddleOCR-json/assets/44918749/379285e1-f938-4164-b0e8-adc71a591c7a)
请问上面代码中的第68行PPOCR *ppocr;   是如何编译通过的，并没有引入相关的头文件呢。期待各位大佬的回复。

**Comment by hiroi-sora** [comment]
你当前看的这个文件是`task.h`，引用了 `namespace PaddleOCR` 和 `class PPOCR` 。这两个东西是在 [paddleocr.h](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/cpp/include/paddleocr.h) 中定义的。

对于C++，`#include <xxx.h>` 可以简单理解为将这行代码替换为 `xxx.h` 文件中的内容。因此，cpp中引入头文件时，只需：
```
#include <include/paddleocr.h> // 先引入 paddleocr
#include <include/task.h> // 再引入 task
```
就可以让编译器正确地识别 `task.h` 中引用的元素。

---

你可以试试这个小demo：

头文件1：`test1.h`
```
int i1 = 1111;
```
头文件2：`test2.h`
```
int i2 = i1 + 2222;
```
`main.cpp`
```
#include <iostream>
#include "test1.h"  // 尝试注释掉这行，就会报错 i1 未定义。
#include "test2.h"

int main()
{
    std::cout << "i2=" << i2 << std::endl;
}
```

**Comment by KyleWang-Hunter** [comment]
> 你当前看的这个文件是`task.h`，引用了 `namespace PaddleOCR` 和 `class PPOCR` 。这两个东西是在 [paddleocr.h](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/cpp/include/paddleocr.h) 中定义的。
> 
> 对于C++，`#include <xxx.h>` 可以简单理解为将这行代码替换为 `xxx.h` 文件中的内容。因此，cpp中引入头文件时，只需：
> 
> ```
> #include <include/paddleocr.h> // 先引入 paddleocr
> #include <include/task.h> // 再引入 task
> ```
> 
> 就可以让编译器正确地识别 `task.h` 中引用的元素。
> 
> 你可以试试这个小demo：
> 
> 头文件1：`test1.h`
> 
> ```
> int i1 = 1111;
> ```
> 
> 头文件2：`test2.h`
> 
> ```
> int i2 = i1 + 2222;
> ```
> 
> `main.cpp`
> 
> ```
> #include <iostream>
> #include "test1.h"  // 尝试注释掉这行，就会报错 i1 未定义。
> #include "test2.h"
> 
> int main()
> {
>     std::cout << "i2=" << i2 << std::endl;
> }
> ```

感谢大佬的耐心回复
