### ISSUE TITLE
是否修改CMakeLists目标名字

### ISSUE THREAD

**Issue by Gavin1937** [hiroi-sora/PaddleOCR-json#109]
目前本项目是套用的PaddleOCR官方的模板CMakeLists.txt，不过没有更改目标名字，导致输出的可执行文件的名字也是默认的。

在这一行：
https://github.com/hiroi-sora/PaddleOCR-json/blob/504cc1e06a443f38e4521ad6f3ffec9e7f22f9cc/cpp/CMakeLists.txt#L14-L16

其实可以直接把上面这行给改成：
```
set(DEMO_NAME "PaddleOCR-json") 
```

这样一来就不需要手动重命名了。也不需要修改 Visual Studio 的目标名。

如果需要的话我可以提交个PR

**Comment by hiroi-sora** [comment]
善哉，改。

**Comment by Gavin1937** [comment]
那我发个PR
