### ISSUE TITLE
[Linux] Python api 无法从socket server接受到数据

### ISSUE THREAD

**Issue by Gavin1937** [hiroi-sora/PaddleOCR-json#114]
这里我用的 PPOCR_api.py 是基于最新 main branch 里面的 https://github.com/hiroi-sora/PaddleOCR-json/blob/c19f3a2aa4bfb7bc7c08966465ec726c661e4f18/api/python/PPOCR_api.py

```sh
套接字服务器初始化成功。127.0.0.1:58267
初始化OCR成功，进程号为191591

测试图片路径：/mnt/c/Users/user/Dev/PaddleOCR-json/api/python/test.jpg

示例1-图片路径识别结果（原始信息）：
{'code': 905, 'data': '识别器输出值反序列化JSON失败。异常信息：[Expecting value: line 1 column 1 (char 0)]。原始内容：[]'}

示例1-图片路径识别结果（格式化输出）：
图片识别失败。错误码：905，错误信息：识别器输出值反序列化JSON失败。异常信息：[Expecting value: line 1 column 1 (char 0)]。原始内容：[]

示例2-剪贴板识别结果：
图片识别失败。错误码：902，错误信息：连接被拒绝

示例3-字节流识别结果：
图片识别失败。错误码：902，错误信息：连接被拒绝

示例4-PIL Image 识别结果：
图片识别失败。错误码：901，错误信息：子进程已崩溃。
###  PPOCR引擎子进程关闭！
```

在示例1那里就出错了，我往这个 while 循环里加了个print之后显示 `chunk` 里面是空的。

https://github.com/hiroi-sora/PaddleOCR-json/blob/c19f3a2aa4bfb7bc7c08966465ec726c661e4f18/api/python/PPOCR_api.py#L192-L197

但是手动在后台开一个PaddleOCR-json进程，再把这里的 `clientSocket.connect()` 给改成那个手动进程的 ip 和 port 就能用了

https://github.com/hiroi-sora/PaddleOCR-json/blob/c19f3a2aa4bfb7bc7c08966465ec726c661e4f18/api/python/PPOCR_api.py#L185-L189 

可能是到这一步的时候 PaddleOCR-json 还没准备好？

**Comment by hiroi-sora** [comment]
示例1 `ipcMode="socket"`模式，在Windows下是正常的。在Linux中，我认为可以检查下：

- Python API 获取的 ip : port 是否正确？
- Python提交第一次任务的时候，PaddleOCR-json 是否已经准备好？（C++代码发送 `Socket init completed. ` 的时候，是否确保TCP服务端已开启？）
- Python如果加个sleep，预留一些时间，是否可行？
- C++ 手动开启的独立进程，和被Python拉起的子进程，是否会存在差别？（假设 a.py 可以TCP调用手动拉起的OCR进程。那么，用另一个py脚本拉起OCR进程，用 a.py 调用它，是否可行？）

**Comment by Gavin1937** [comment]
已经找到问题并解决了（应该算是绕过这个问题。。。）

当PaddleOCR-json：
  * 运行在WSL下
  * 并且以套接字服务器的模式启动
  * 并且使用 python `subprocess.Popen()` 来以子进程的形式启动
  * 并且将所有的 `stdout` 输出导入 `subprocess.PIPE`

下面这行 `std::cout` 会将整个服务器阻塞。

https://github.com/hiroi-sora/PaddleOCR-json/blob/763311cb91481917dbae86cac8cc3c1a171d40fe/cpp/src/task_linux.cpp#L188-L190

不知道是因为python `subprocess.Popen()` 在WSL下处理 stdout PIPE 有问题、还是WSL本身的 stdout 就有问题、或者是什么其他的问题。

不过因为这个阻塞，下面那行 `send()` 永远无法运行，python api 那边也就无法接收到任何数据了。

把这行 `std::cout` 去掉就没问题了。

**不过这个问题只在WSL里出现，我在另一台ubuntu的机器上完全没问题。**

所以我就直接用CMake检测WSL，如果是WSL就设置一个compiler flag用来去掉那个 `std::cout`

https://github.com/Gavin1937/PaddleOCR-json/blob/2e0aa3640e4f72e971434a9822e319f97517d987/cpp/src/task_linux.cpp#L189-L200

**Comment by hiroi-sora** [comment]
> 下面这行 std::cout 会将整个服务器阻塞

如何将它换成 std::cerr 呢？

我记得cout堵塞的问题，以前也遇到过，是out输出流缓冲区满了导致停在这行。

换成cerr，因为python端没有监听这个接口，所以不存在缓冲区满的问题，同时开发者也能在控制台正常看到调试输出。

你试试是否可行，可以的话，就不用判断 WSL 那么麻烦了。

**Comment by Gavin1937** [comment]
改成 cerr 确实可以，不过我有预感之后还会遇到更多WSL相关的特例。所以我觉得还是留下这个WSL检测的机制比较好。它也不麻烦，只是设置一个 compiler flag而已。

改成这样怎么样？

```cpp
#ifdef UNDER_WSL
            // 当运行在WSL下时，如果使用 python subprocess.Popen() 来以子进程的形式启动这个程序，
            // 并且将所有的 stdout 输出导入 subprocess.PIPE 时，
            // 下面这一行 std::cout 会将整个服务器阻塞。
            // 于是我们用 CMake 去检测 WSL 并设置这个 UNDER_WSL 的 compiler flag。
            // 如果在 WSL 下就使用 std::cerr 。
            std::cerr << strOut << std::endl;
#else
            std::cout << strOut << std::endl;
#endif
```

**Comment by hiroi-sora** [comment]
在项目里使用WSL检测机制没问题。

不过单纯就这个问题而言，用 `std::cout` 确实不规范，是我当初的疏忽。TCP模式下，所有调试输出都应该用 `std::cerr` ，以降低出问题的风险。

不然WSL下可能有坑，别的某个Linux发行版下可能也有类似的坑。

我建议 task_win32 也一并改掉它
https://github.com/hiroi-sora/PaddleOCR-json/blob/763311cb91481917dbae86cac8cc3c1a171d40fe/cpp/src/task_win32.cpp#L333

**Comment by Gavin1937** [comment]
> 我记得cout堵塞的问题，以前也遇到过，是out输出流缓冲区满了导致停在这行。

这应该不是缓冲区满了的问题，我手动在cout之前加上 `std::cout.flush()` 或者 `std::cout.clear()` 也没用

**Comment by hiroi-sora** [comment]
> 我手动在cout之前加上 std::cout.flush() 或者 std::cout.clear() 也没用

可能是python端的问题

**Comment by Gavin1937** [comment]
> 我建议 task_win32 也一并改掉它

确实

既然都用到套接字了，那客户端那边也应该用套接字去收发数据。只是最开始需要用 stdout 来识别ip和端口而已。

这里的 cout 应该全部换成 cerr

**Comment by Gavin1937** [comment]
已经修改了
