### ISSUE TITLE
一些关于剪切板的讨论

### ISSUE THREAD

**Issue by Gavin1937** [hiroi-sora/PaddleOCR-json#116]
### 1. 

PaddleOCR-json的剪切板读取文件的功能是建立在ocr引擎与前端软件在同一个文件系统的前提下的。

不过如果把PaddleOCR-json跑在另一个服务器上，这个剪贴板的功能就变得不太合理了。

我觉得应该新增一个新的配置参数来开启/关闭剪切板。

比如说 `-enable_clipboard=true`，默认是 true ，然后用户可以将其设置成 false

接着只需要在 `imread_u8()` 里面检查一下这个参数就行了：

```cpp
// 剪贴板启用并且为剪贴板任务
if (FLAGS_enable_clipboard && pathU8 == "clipboard")
    return imread_clipboard(flag);

// 剪贴板禁用并且为剪贴板任务
else if (!FLAGS_enable_clipboard && pathU8 == "clipboard")
    // 报错

// pathU8 为正常路径
```

### 2.

我不太理解：

既然PaddleOCR-json是一个OCR引擎，那它真的需要去做读取剪贴板的工作吗？

如果把读取剪贴板的工作全部放在引擎的前端（比如Umi-OCR）会不会更合理一些呢？

当然，现在也不应该直接删除剪贴板相关的功能，其他软件可能也在用着这个功能。

我只想带起这个讨论。

**Comment by hiroi-sora** [comment]
> 其他软件可能也在用着这个功能

没错，这是一个历史遗留问题。 Umi-OCR v1 版本中，是靠引擎本身去获取剪贴板数据的。

不过在现在的 Umi-OCR v2.x ，管理剪贴板的工作已经交给了前端。

服务端去读剪贴板确实是不必要，且不安全的行为。后续版本，我认为可以移除该功能了。

- PaddleOCR-json 的 Windows 版本，该功能相关的代码可以保留，但弄个flag，默认 **不编译** 这段代码。如果老用户确实有依赖，则可自行调整、编译。
- Linux版本，则无需开发剪贴板功能。

**Comment by Gavin1937** [comment]
确实，移除这个功能会更好。

> 该功能相关的代码可以保留，但弄个flag

这个简单，我下个PR给加上。

> Linux版本，则无需开发剪贴板功能。

Linux不像Windows或者Mac，它的“剪贴板”设计得很复杂。把全部的剪贴板读取功能交由其他的跨平台library会更方便。

像Umi-OCR可以直接用[Qt的QClipboard](https://doc.qt.io/qt-6/qclipboard.html)去跨平台支持剪贴板。

**Comment by hiroi-sora** [comment]
嗯，Umi v2 已经考虑到了剪贴板等机制的跨平台。

我这两天会研究一下Umi的linux环境部署

**Comment by Gavin1937** [comment]
剪贴板的移除已经做好了，不过更改的内容比较多，所以暂时先不发PR。我把所有的更改都放在下面这个branch里，方便cherry pick。麻烦作者检查一下看看有哪些是不需要或者要更改的吧。完了我整理一下再发PR

https://github.com/Gavin1937/PaddleOCR-json/commits/clipboard/

具体的更改：

* 给task_linux.cpp的imread_u8增加更好的异常处理
* 移除task_linux.cpp中的剪贴板相关内容
* 更新CMakeLists.txt，新增一条参数 `-DENABLE_CLIPBOARD`
* 禁用task_win32.cpp下的剪贴板相关内容
* 禁用task.h下的剪贴板相关宏
* 在task.cpp中添加一个新的 stdout 输出 `"OCR clipboard enbaled."`，添加在 `OCR single image mode` 之前。这样方便其他程序识别剪贴板是否启用（只在Windows下有效）。
* 更新python api、demo、和文档剪贴板相关内容：
  * api会在初始化时检测剪贴板是否启用并以此来决定 `runClipboard()` 是否能用。如果剪贴板禁用则抛一个异常
  * 为api新增一个方法 `isClipboardEnabled()` 来告诉用户剪贴板启用情况
  * demo1会更具剪贴板启用情况来选择是否显示剪贴板的demo
* 更新powershell api、demo剪贴板相关内容：
  * api会在初始化时检测剪贴板是否启用并以此来决定 `runClipboard()` 是否能用。如果剪贴板禁用则抛一个异常
  * 为api新增一个方法 `isClipboardEnabled()` 来告诉用户剪贴板启用情况
  * demo会更具剪贴板启用情况来选择是否显示剪贴板的demo
* 更新node.js api剪贴板相关内容：
  * node.js 只会在 `image_path` 设置为 null 的时候用剪贴板，我就直接把它换成抛一个异常了。
* 整理了一下现有文档中有关剪贴板的内容，主要是隐藏和删除剪贴板的内容
* 为Windows和Linux构建文档更新CMake参数和剪贴板相关内容

**Comment by Gavin1937** [comment]
除了node.js我这边没法测试以外其他所有的更改（C++、python、powershell）都测试过能用了。

**Comment by hiroi-sora** [comment]
OK，我看过了，没有可见的问题。

v1.3 版暂时保留剪贴板相关代码。未来的 v1.4 或更高的版本，我会跟进 PaddleOCR 官方 v2.7 或最新的版本，那时候可能完全移除剪贴板相关的代码。

**Comment by Gavin1937** [comment]
已经发PR了
