### ISSUE TITLE
项目在Windows MSVC下无法以debug模式链接

### ISSUE THREAD

**Issue by Gavin1937** [hiroi-sora/PaddleOCR-json#124]
这是我在测试的时候发现的，用的是最新的main branch。

在debug模式下，编译没有问题，但是在链接时MSVC会报错，主要是下面这两种错误：

```
glog.lib(logging.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in args.obj [PaddleOCR-json\cpp\build\PaddleOCR-json.vcxproj]
glog.lib(logging.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in args.obj [PaddleOCR-json\cpp\build\PaddleOCR-json.vcxproj]
```

这报错简单来说就是：MSVC基于项目源码 `args.cpp` 所编译的 `args.obj` 的编译参数与静态链接库 `glog.lib` 不同，所以MSVC无法完成链接。
而这个 `glog.lib` 是从paddle_inference里来的，估计是以release的模式编译的。
换句话说，这个问题无法修复。因为paddle_inference里面所有东西应该都是以release模式编译的，如果想在debug模式下编译项目则需要将paddle_inference也给一同以debug模式编译一遍。

**Comment by hiroi-sora** [comment]
是滴，paddleocr的文档和本项目的windows构建文档里都提到了，编译模式需要改为release。

**Comment by Gavin1937** [comment]
嗯，我确实没注意到。之后就不测试Windows debug模式了

**Comment by aijyo** [comment]
> 是滴，paddleocr的文档和本项目的windows构建文档里都提到了，编译模式需要改为release。

这是为什么啊，有时候我想调试下，发现就是不行。。

**Comment by Gavin1937** [comment]
@aijyo 因为我们链接的paddle_inference.dll是release版的，没有debug信息，msvc就不给你链接了。
你可以研究一下msvc如何在这种情况下强行使用debug模式链接。
或者找找paddleocr官方有没有放出debug版的paddle_inference.dll，如果没有的话就只能自己编译一个debug版的paddle_inference了

**Comment by aijyo** [comment]
> [@aijyo](https://github.com/aijyo) 因为我们链接的paddle_inference.dll是release版的，没有debug信息，msvc就不给你链接了。 你可以研究一下msvc如何在这种情况下强行使用debug模式链接。 或者找找paddleocr官方有没有放出debug版的paddle_inference.dll，如果没有的话就只能自己编译一个debug版的paddle_inference了

解决了，禁止优化，禁止inline  生成调试信息，调试信息改为ZI  就能一行一行调试代码了。
