### ISSUE TITLE
什么时候可以支持docker一键部署，可以的话感觉能瞬间火起来

### ISSUE THREAD

**Issue by zclcz** [hiroi-sora/PaddleOCR-json#127]
什么时候可以支持docker一键部署，可以的话感觉能瞬间火起来，大概什么时候可以支持呢

**Comment by hiroi-sora** [comment]
已试验性支持 Docker 部署，详见文档：

https://github.com/hiroi-sora/PaddleOCR-json/blob/main/cpp/README.md#%E4%BD%BF%E7%94%A8-docker-%E9%83%A8%E7%BD%B2

**Comment by zclcz** [comment]
部署完后 怎么使用api调用呢

**Comment by hiroi-sora** [comment]
你好，可以使用 [Python API](https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python) ，参考文档中的 **使用套接字模式连接到远程服务器** 部分。

比方说Docker部署在本机上，容器暴露的端口是1234，那么：
```python
ocr = GetOcrApi(r"remote://127.0.0.1:1234", ipcMode="socket")
```
如果Docker部署在另一台机器上，那么 `127.0.0.1` 换成那台机器的ip。

**Comment by zclcz** [comment]
我后端语言是Java  想问一下PaddleOCR-json-java-api可以用吗 但是demo里使用的是可执行exe文件 那么服务调用的话怎么改呢

**Comment by hiroi-sora** [comment]
> 我后端语言是Java 想问一下PaddleOCR-json-java-api可以用吗

也是可以的， **使用套接字服务方式初始化 OCR** ，无需传入exe地址，arguments留空即可。

**Comment by Gavin1937** [comment]
> 那么服务调用的话怎么改呢

这里需要注意docker镜像在构建时会默认禁用从剪贴板和路径读取图片的功能。所以java api的`runOcr`和`runOcrOnClipboard`这两个方法是用不了的（具体请参考文档）。你需要直接传输图片字节流或者是base64字符串。
