### ISSUE TITLE
docekr部署成功，使用javaapi调用，第二次报错 java.net.SocketException: 你的主机中的软件中止了一个已建立的连接。

### ISSUE THREAD

**Issue by zclcz** [hiroi-sora/PaddleOCR-json#129]
看了其他issue 给出的方案是重新创建socket连接，我的写法是socket在服务初始化就创建了链接并维护成全局可复用的了，结果第二次调用就出现了断连情况，请问必须每次调用的都得重新建立连接吗

**Comment by Gavin1937** [comment]
是的，客户端每次与PaddleOCR-json字套接服务器通信时都要重新建立连接。

底层字套接服务器处理客户端连接的循环在这里：

https://github.com/hiroi-sora/PaddleOCR-json/blob/dc799911788fceebfe5b3aa9a37e405fa1859c3a/cpp/src/task_linux.cpp#L138-L207

注意第206行，不管当前与客户端的通信结果如何（是否收到完整数据、是否完成OCR、OCR结果如何），服务器都会在循环的末尾断开与客户端的连接。这就是为什么第二次调用会出现断连的情况。

客户端的实现可以参考python api的写法：

https://github.com/hiroi-sora/PaddleOCR-json/blob/dc799911788fceebfe5b3aa9a37e405fa1859c3a/api/python/PPOCR_api.py#L242-L265

每次发数据就创建一个连接，完了就关掉，下次重新再创建一个。
