### ISSUE TITLE
关于在java环境调用本地linux下的ocr服务问题

### ISSUE THREAD

**Issue by SMSshuai** [hiroi-sora/PaddleOCR-json#130]
你好请问，应该如何调用linux环境的cor，java代码调用win10环境下的本地ocr是正常的，linux部署后，直接测试是正常的，但是使用提供的java测试代码启动会失败，提示内容为空日志pd---这里输出的是空
![4a666444ca14728856077f5662724e14](https://github.com/hiroi-sora/PaddleOCR-json/assets/66891829/a485ae03-5461-4ed4-9209-9ce76d827c86)

**Comment by Gavin1937** [comment]
你好，这种情况有可能是java主程序在启动PaddleOCR-json时没有找到它的依赖库，或者是PaddleOCR-json找不到模型库而导致的。

你可以尝试：
1. 传入PaddleOCR-json包内的 `run.sh` 脚本的路径到 `exePath` 参数里。这个脚本会自动寻找所需的依赖来启动PaddleOCR-json。
2. 传入一个参数 `models_path` 到 Ocr 对象里。[你可以用这个参数来指定模型库的位置](https://github.com/hiroi-sora/PaddleOCR-json/tree/main?tab=readme-ov-file#%E5%B8%B8%E7%94%A8%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)。模型库是PaddleOCR-json包内的 `models` 文件夹。

比如这样：

```java
        // 可选的配置项
        Map<String, Object> arguments = new HashMap<>();
        arguments.put("models_path", "/path/to/PaddleOCR-json_v.1.4.0_debian_gcc_x86-64/models");

        // 初始化 OCR：使用本地进程或者套接字服务器
        // 本地进程: new Ocr(new File(exePath), arguments)
        // paddleocr_json 的可执行文件所在路径
        String exePath = "/path/to/PaddleOCR-json_v.1.4.0_debian_gcc_x86-64/run.sh";
```

**Comment by SMSshuai** [comment]
> 你好，这种情况有可能是java主程序在启动PaddleOCR-json时没有找到它的依赖库，或者是PaddleOCR-json找不到模型库而导致的。
> 
> 你可以尝试：
> 
> 1. 传入PaddleOCR-json包内的 `run.sh` 脚本的路径到 `exePath` 参数里。这个脚本会自动寻找所需的依赖来启动PaddleOCR-json。
> 2. 传入一个参数 `models_path` 到 Ocr 对象里。[你可以用这个参数来指定模型库的位置](https://github.com/hiroi-sora/PaddleOCR-json/tree/main?tab=readme-ov-file#%E5%B8%B8%E7%94%A8%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)。模型库是PaddleOCR-json包内的 `models` 文件夹。
> 
> 比如这样：
> 
> ```java
>         // 可选的配置项
>         Map<String, Object> arguments = new HashMap<>();
>         arguments.put("models_path", "/path/to/PaddleOCR-json_v.1.4.0_debian_gcc_x86-64/models");
> 
>         // 初始化 OCR：使用本地进程或者套接字服务器
>         // 本地进程: new Ocr(new File(exePath), arguments)
>         // paddleocr_json 的可执行文件所在路径
>         String exePath = "/path/to/PaddleOCR-json_v.1.4.0_debian_gcc_x86-64/run.sh";
>         try (Ocr ocr = new Ocr(new File(exePath), arguments)) {
> ...
> ```

没有调试成功~不过这个程序在win环境确实好用，速度很快质量也很好。

**Comment by Gavin1937** [comment]
这有点奇怪，如果你已经可以在linux环境下使用PaddleOCR-json，那java api也应该可以调用成功。

你可以尝试一下：

1. [下载最新的 alpha.2 版本](https://github.com/Gavin1937/PaddleOCR-json/releases/tag/v1.4.0-alpha.2)。昨天刚刚更新的，修了一些bug并且让 `run.sh` 去自动寻找使用软件包内的默认模型库（你同样可以用 `models_path` 参数来覆盖它）。
2. 在你的java程序的路径下，直接用 `run.sh` 来跑一次OCR，看看有没有问题。

比如这样，最好全程用绝对路径

```sh
~/my-java-app$ /path/to/PaddleOCR-json_v1.4.0-alpha.2_debian_gcc_x86-64/run.sh -image_path="/path/to/image.png"
```

java api是将PaddleOCR-json以子进程的形式启动，然后直接通过管道进行通讯的。只要java api启动引擎的参数和你在bash里的一致，那就不应该出问题。
