### ISSUE TITLE
v4版本的轻量化模型替换后无法初始化引擎

### ISSUE THREAD

**Issue by yang-521** [hiroi-sora/PaddleOCR-json#133]
轻量模型目前官方已经更新到V4，我下载回来后将配置文件config_chinese.txt修改成了v4的参数，v3和v4都在时能够初始化，但v3删除后就无法正常初始化了，封装好的引擎模型是固定的吗

**Comment by hiroi-sora** [comment]
你好，引擎中模型库没有写死，允许替换。可能是你编写配置的格式错误。请仔细参考本项目文档。

另外，本项目基于ppocr v2.7版本引擎，暂不兼容 v4 模型库（只兼容v2、v3）。如果你想使用 v4 模型库，可以使用隔壁 RapidOCR-json ，它发行版中自带的就是v4模型。

**Comment by yang-521** [comment]
那这个项目最近有更新计划吗

**Comment by yang-521** [comment]
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/122206917/fad2017e-5a4b-4d23-90fe-d40d63d86de1)
这个参数配置应该没问题吧，左边是轻量化的，右边是完整版的V4模型，我文件夹里的V3模型没删除的时候两个初始化都正常，删除了两个都不行了，但我的配置参数里边并没有去引用这个V3模型，就挺奇怪的，是封装好的引擎捕获异常后尝试使用V3吗

![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/122206917/703da54b-8a41-4ee3-8de7-53e9d31576da)

**Comment by hiroi-sora** [comment]
短期内，我可能没有时间做大幅更新。
