### ISSUE TITLE
请教一下，我使用docker的形式部署·，在构建阶段下载deb.debian.org的资源非常慢，构建一次需要3个小时左右，且在最后阶段出现了无法连接github的错误，我尝试切换了很多镜像源，但效果都不佳，最后都会构建失败，我对docker使用不太熟悉，想求教下我该如何配置网络可以解决这个问题

### ISSUE THREAD

**Issue by saberorlancer** [hiroi-sora/PaddleOCR-json#150]
<img width="1096" alt="微信图片_20240909160452" src="https://github.com/user-attachments/assets/986f2545-e60c-426c-8d53-d5cafde069e1">

**Comment by saberorlancer** [comment]
我搜索教程将 /etc/docker/daemon.json 修改为

**Comment by saberorlancer** [comment]
我参考教程将 /etc/docker/daemon.json 修改为
![image](https://github.com/user-attachments/assets/b36a25a6-f30d-4fac-81e0-486764b039e5)
后，一阶段下载1个g资源的速度显著提升，二阶段下载387MB资源时速度还是提不起来
![image](https://github.com/user-attachments/assets/2178f707-21e8-4792-ba38-1e0ed42f014a)，等我执行完了看下结果

**Comment by hiroi-sora** [comment]
你好，个人建议 不修改镜像源，用代理解决。

参考步骤：

1. 打开文件 `/etc/systemd/system/docker.service.d/http-proxy.conf` 。如果不存在则创建。
2. 向文件中添加下列语句。具体地址填你的代理端。
```
[Service]
Environment="HTTP_PROXY=http://127.0.0.1:7897"
Environment="HTTPS_PROXY=http://127.0.0.1:7897"
```
3. 重启服务。
```
sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by saberorlancer** [comment]
> 你修改好，个人建议不镜像源，用代理解决。
> 
> 参考步骤：
> 
> 1. 打开文件`/etc/systemd/system/docker.service.d/http-proxy.conf`。如果不存在则创建。
> 2. 向文件中添加以下语句。具体地址填你的代理端。
> 
> ```
> [Service]
> Environment="HTTP_PROXY=http://127.0.0.1:7897"
> Environment="HTTPS_PROXY=http://127.0.0.1:7897"
> ```
> 
> 3. 重新启动服务。
> 
> ```
> sudo systemctl daemon-reload
> sudo systemctl restart docker
> ```

感谢，我已成功构建并启动，但我在使用java api 调用 3746端口时 出现以下错误 ，是我少了什么配置吗OcrResponse{code=403, data=null, msg='No valid tasks.', hotUpdate='null'}

**Comment by saberorlancer** [comment]
已解决，调用成功
