### ISSUE TITLE
作者你好。能否把管道传入的json格式的文本打印一份

### ISSUE THREAD

**Issue by xxdoc** [hiroi-sora/PaddleOCR-json#16]
我用的vb语音，需要自己构建json格式进行管道参数传递。我想知道json格式的结构。能否打印一份json格式的例子，这样我就知道怎么传递参数了。py的我不了解谢谢。

**Comment by xxdoc** [comment]
是不是就是这个格式 {"image_dir": "\u6D4B\u8BD5\u56FE\u7247\\test 1.jpg"}

**Comment by hiroi-sora** [comment]
> 是不是就是这个格式 {"image_dir": "\u6D4B\u8BD5\u56FE\u7247\test 1.jpg"}

是滴。

[文档已补充json格式样例](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/docs/%E8%AF%A6%E7%BB%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md#-%E9%80%9A%E8%BF%87%E7%AE%A1%E9%81%93%E4%BC%A0json%E5%BB%BA%E8%AE%AE)

**Comment by xxdoc** [comment]
{"code":100,"data":[{"box":[0,156,26,158,23,231,0,229],"score":0.35962218046188354,"text":"O"},{"box":[312,161,655,161,655,184,312,184],"score":0.9442936182022095,"text":"姝︽眽甯傛椽灞卞尯涓尰鍖婚櫌"},{"box":[1267,175,1300,175,1300,196,1267,196],"score":0.9259291291236877,"text":"妗戦湶"},{"box":[1471,173,1563,173,1563,193,1471,193],"score":0.899527370929718,"text":"鎯犺€?鐩戞姢浜?},{"box":[945,184,979,184,979,203,945,203],"score":0.9988371729850769,"text":"鍒嗙骇"},{"box":[1087,184,1156,184,1156,203,1087,203],"score":0.8866327404975891,"text":"鎺ヨЕ鏂瑰紡"},{"box":[1263,194,1300,194,1300,215,1263,215],"score":0.998431921005249,"text":"绋嬪害"},{"box":[1341,186,1409,186,1409,205,1341,205],"score":0.951829195022583,"text":"鍖诲笀寤鸿"},{"box":[309,196,652,196,652,220,309,220],"score":0.9649718999862671,"text":"娲北鍖虹彏鍗楄绀惧尯鍗敓鏈嶅姟涓績"},{"box":[1451,194,1585,191,1585,210,1451,213],"score":0.9755198955535889,"text":"锛堝湪鐩稿簲鏍忕洰鍒掑嬀锛?},{"box":[984,222,1123,220,1123,240,984,241],"score":0.9740139842033386,"text":"鍙ｆ帴瑙︽垨鍠傚吇鍔ㄧ墿"},{"box":[1304,220,1448,222,1448,241,1304,240],"score":0.9924584031105042,"text":"鍙ｇ‘璁ゆ帴瑙︽柟寮忓彲"},{"box":[950,233,973,233,973,248,950,248],"score":0.8500528335571289,"text":"I绾?},{"box":[380,234,577,234,577,259,380,259],"score":0.9924824833869934,"text":"棰勯槻鐙傜姮鐤嫍鐥呭巻"},{"box":[1277,234,1290,234,1290,246,1277,246],"score":0.6243101954460144,"text":"鏃?},{"box":[1455,231,1581,231,1581,250,1455,250],"score":0.9370200037956238,"text":"鍚屾剰鍙ｄ笉鍚屾剰"},{"box":[988,241,1123,241,1123,259,988,259],"score":0.9408541917800903,"text":"鍙ｅ畬濂界殑鐨偆琚垟"},{"box":[1307,241,1405,241,1405,260,1307,260],"score":0.9543664455413818,"text":"闈狅紝鏃犻渶澶勭疆"},{"box":[984,266,1144,266,1144,288,984,288],"score":0.9349782466888428,"text":"鍙ｈ８闇茬殑鐨偆琚交鍜?},{"box":[1309,267,1398,267,1398,286,1309,286],"score":0.9450438618659973,"text":"鍙ｅ鐞嗕激鍙?},{"box":[145,269,294,269,294,299,145,299],"score":0.7373499870300293,"text":"濮撳悕锛氥€併€?},{"box":[517,274,591,280,589,302,515,297],"score":0.7647742629051208,"text":"浣撻噸锛?"},{"box":[284,276,358,276,358,295,284,295],"score":0.8305542469024658,"text":"鎬у埆锛?},{"box":[374,276,426,276,426,295,374,295],"score":0.9399458765983582,"text":"骞撮緞锛?},{"box":[1455,267,1585,267,1585,286,1455,286],"score":0.9312213659286499,"text":"鍙ｅ悓鎰忓彛涓嶅悓鎰?},{"box":[605,278,636,278,636,299,605,299],"score":0.9874989986419678,"text":"(kg)"},{"box":[945,278,979,278,979,297,945,297],"score":0.6839918494224548,"text":"II绾?},{"box":[1270,280,1300,280,1300,293,1270,293],"score":0.9129589796066284,"text":"杞诲害"},{"box":[986,288,1188,288,1188,306,986,306],"score":0.932542622089386,"text":"鍙ｆ棤鍑鸿鐨勮交寰姄浼ゆ垨鎿︿激"},{"box":[135,290,449,293,449,349,135,346],"score":0.46063247323036194,"text":"鏁磋瘖闄勫洜17, 锛?鍙婇泦绯栧彂鑱旂郴鏂瑰紡銆?},{"box":[1307,285,1586,285,1586,307,1307,307],"score":0.9077137112617493,"text":"鎺ョ鐙傜姮鐥呯柅鑻楀彛鍚屾剰鍙ｄ笉鍚屾剰"},{"box":[460,299,572,304,570,328,458,323],"score":0.6602796912193298,"text":"13796233367"},{"box":[984,314,1256,314,1256,337,984,337],"score":0.9104102253913879,"text":"鍙ｅ崟澶勬垨澶氬璐┛鎬х毊鑲ゅ挰浼ゆ垨鎶撲激"},{"box":[147,328,207,328,207,347,147,347],"score":0.984303891658783,"text":"涓€銆佷富璇?},{"box":[982,335,1110,332,1110,356,982,360],"score":0.8788419365882874,"text":"鐮存崯鐨偆琚垟"},{"box":[1311,335,1398,335,1398,354,1311,354],"score":0.8527108430862427,"text":"鍥藉鐞嗕激鍙?},{"box":[1458,335,1583,335,1583,353,1458,353],"score":0.9780286550521851,"text":"鍥藉悓鎰忓彛涓嶅悓鎰?},{"box":[172,351,358,349,358,373,172,375],"score":0.9306438565254211,"text":"浼や汉鍔ㄧ墿锛氱嫍銆併€侀紶鍏朵粬"},{"box":[403,349,584,353,584,375,403,372],"score":0.855623185634613,"text":"鍜激銆佹姄缁ｃ€佽垟鍙婄矘鑶滀激鍙?},{"box":[938,354,1194,344,1195,379,940,389],"score":0.866878867149353,"text":"XU绾у悗寮€鏀炬€т激鍙ｆ垨绮樿啘琚薄鏌?},{"box":[1309,353,1462,353,1462,375,1309,375],"score":0.9684368371963501,"text":"娉ㄥ皠鐙傜姮鐥呭厤鐤?},{"box":[0,363,23,363,23,389,0,389],"score":0.1452185958623886,"text":"闂?},{"box":[1270,363,1304,363,1304,382,1270,382],"score":0.9951258897781372,"text":"涓ラ噸"},{"box":[1453,354,1585,354,1585,373,1453,373],"score":0.8975268006324768,"text":"鍙ｅ悓鎰忓彛涓嶅悓鎰?},{"box":[984,373,1258,372,1258,394,984,396],"score":0.946560800075531,"text":"鍙ｅ垽瀹氫负II绾ф毚闇蹭笖鍏嶇柅鍔熻兘浣庝笅鑰?},{"box":[138,375,398,382,398,412,138,405],"score":0.7974086403846741,"text":"浜屻€佺幇鐥呭彶鍙婁綋鏍兼鏌ワ細9 16Pn"},{"box":[1315,373,1370,373,1370,393,1315,393],"score":0.9967942833900452,"text":"鐞冭泲鐧?},{"box":[986,393,1256,391,1256,413,986,415],"score":0.9175196886062622,"text":"鍙I绾ф毚闇蹭綅浜庡ご闈㈤儴涓旇嚧浼ゅ姩鐗╀笉"},{"box":[1311,389,1453,389,1453,412,1311,412],"score":0.9553702473640442,"text":"鍙ｆ敞灏勭媯鐘梾鐤嫍"},{"box":[303,400,465,400,465,436,303,436],"score":0.7904244661331177,"text":"2銆佸彈浼ら儴浣嶏細澶崄"},{"box":[1458,393,1585,393,1585,412,1458,412"score":0.8650175929069519,"text":"鍥藉悓鎰忓彛涓嶅悓鎰?},{"box":[163,410,296,396,300,429,167,443],"score":0.7426076531410217,"text":"1銆佸彈浼ゆ椂闂?022"},{"box":[488,410,620,413,620,438,488,434],"score":0.8102735280990601,"text":"鑷澶勭悊锛堛€侀锛?},{"box":[1007,415,1091,415,1091,433,1007,433],"score":0.9729182124137878,"text":"纭畾鍋ュ悍鏃?},{"box":[165,433,426,436,426,460,165,457],"score":0.9097062945365906,"text":"3銆佷激鍙ｆ儏鍐碉細琛ㄧ毊銆佸涓嬨€佽倢鑲夈€佸叾浠栵細"},{"box":[940,446,1400,446,1400,469,940,469],"score":0.9720134735107422,"text":"銆愭帴绉嶇蹇屻€?.鐢变簬鐙傜姮鐥呮槸鑷存鎬х柧鐥咃紝鏆撮湶鍚庡厤鐤棤浠讳綍绂佸繉鐥?},{"box":[136,462,302,462,302,485,136,485],"score":0.9379207491874695,"text":"涓夈€佹棦寰€鍙诧細鐙傝嫍鎺ョ鍙?},{"box":[357,462,405,462,405,488,357,488],"score":0.5339851379394531,"text":"鏃?},{"box":[312,466,334,466,334,481,312,481],"score":0.9988961219787598,"text":"鏈?},{"box":[431,464,463,464,463,486,431,486],"score":0.9864413142204285,"text":"鍏朵粬"},{"box":[952,471,1604,469,1604,492,952,493],"score":0.9639127850532532,"text":"2.鏆撮湶鍓嶅厤鐤椂绂佸繉鐥囷細瀵硅鐤嫍鐨勪换浣曟垚鍒嗚繃鏁忚€咃細鎮ｆ€ユ€х柧鐥呫€佷弗閲嶆參鎬х柧鐥呫€佹參鎬х柧鐥呯殑"},{"box":[136,488,218,488,218,507,136,507],"score":0.904771089553833,"text":"鍥涖€佽繃鏁忓彶锛?},{"box":[924,492,1389,490,1389,513,924,514],"score":0.9223126173019409,"text":"鎬ユ€у彂浣滄湡鍜屽彂鐑€咃細鎮ｆ湭鎺у埗鐨勭櫕鐥拰鍏朵粬杩涜鎬х缁忕郴缁熺柧鐥呰€呫€?},{"box":[1,507,8,507,8,521,1,521],"score":0.14696021378040314,"text":"P"},{"box":[135,513,293,513,293,535,135,535],"score":0.9274659752845764,"text":"浜斻€佽瘖鏂垎绾э細1绾ф毚闇?},{"box":[346,514,408,514,408,539,346,539],"score":0.5157995223999023,"text":"鑰崇骇钂搁湶"},{"box":[460,518,524,518,524,537,460,537],"score":0.9787750840187073,"text":"绾ф毚闇?},{"box":[582,520,629,520,629,540,582,540],"score":0.8212383389472961,"text":"榛庨湶鍓?},{"box":[940,521,1606,521,1606,544,940,544],"score":0.9244127869606018,"text":"銆愪笉鑹弽搴斻€?甯歌涓嶈壇鍙嶅簲锛氱孩鑲裤€佺柤鐥涖€佸彂鐥掋€佽交搴﹀彂鐑€佹棤鍔涖€佸ご鐥涖€佺湬鏅曘€佸叧鑺傜棝銆佽倢鑲夌棝銆?},{"box":[133,540,227,540,227,560,133,560],"score":0.9772199392318726,"text":"鍏€侀槻娌绘帾鏂斤細"},{"box":[922,544,1005,544,1005,563,922,563],"score":0.9279916286468506,"text":"鍛曞悙銆佽吂鐥涖€?},{"box":[248,565,490,568,490,591,248,587],"score":0.9619922041893005,"text":"濡傛偅鑰呮嫆缁濆湪鎴戦櫌澶勭悊浼ゅ彛锛岃绛惧瓧"},{"box":[154,566,259,566,259,586,154,586],"score":0.8311765789985657,"text":"L銆佷激鍙ｅ鐞?},{"box":[947,565,1183,565,1183,582,947,582],"score":0.9009849429130554,"text":"2.缃曡涓嶈壇鍙嶅簲锛氫腑搴︿互涓婂彂鐑€?},{"box":[147,589,383,591,383,615,147,613],"score":0.8341081142425537,"text":"2銆佺媯鐘梾浜哄厤鐤悆铔嬬櫧锛岀敓浜у巶瀹?},{"box":[947,586,1613,586,1613,608,947,608],"score":0.9007490277290344,"text":"3.鏋佺綍瑙佷笉鑹弽搴旓細杩囨晱鎬х毊鐤癸紝杩囨晱鎬т紤鍏嬨€佽繃鏁忔€х传缂庛€佽绠＄缁忔€ф按鑲垮拰绁炵粡绯荤粺鍙嶅簲绛?},{"box":[421,598,462,598,462,617,421,617],"score":0.5556823015213013,"text":"44"},{"box":[538,596,581,596,581,617,538,617],"score":0.9970821142196655,"text":"鏀暟"},{"box":[140,613,309,617,309,646,140,643],"score":0.8952361345291138,"text":"3鐮翠激椋庢姉姣掔礌涓嶉棬"},{"box":[941,617,1021,617,1021,636,941,636],"score":0.9539942145347595,"text":"銆愭敞鎰忎簨椤广€?},{"box":[143,646,247,646,247,666,143,666],"score":0.9788151979446411,"text":"4銆佹姉鎰熸煋娌荤枟"},{"box":[941,638,1627,641,1627,664,941,660],"score":0.9756170511245728,"text":"1銆佺洰鍓嶉槻娌荤媯鐘梾鏈€鏈夋晥鐨勬墜娈垫槸瑙勮寖鐨勪激鍙ｅ鐞嗗拰鎺ョ鐙傜姮鐤嫍锛屽繀瑕佹椂浣跨敤鎶楃媯鐘梾浜哄厤鐤悆铔?},{"box":[296,659,335,662,334,685,294,681],"score":0.10274989902973175,"text":"缇庤尪"},{"box":[922,660,1345,664,1345,686,922,683],"score":0.9612420797348022,"text":"鐧斤紝浣嗕笂杩扮殑鎵€鏈夊缃帾鏂藉潎涓嶈兘淇濊瘉鏆撮湶鑰?00%涓嶆儬鐙傜姮鐥?},{"box":[135,671,271,667,271,692,135,695],"score":0.8557129502296448,"text":"5鐙傜姮鐤嫍鍘傚"},{"box":[941,685,1627,688,1627,711,941,707],"score":0.9269442558288574,"text":"2銆佸垽瀹氫负鈪㈢骇鏆撮湶鑰咃紝鎴栫‘璁も叀I绾ф毚闇茶€呬笖鍏嶇柅鍔熻兘浣庝笅鐨勶紝鎴栬€呪叀I绾ф毚闇蹭綅浜庡ご闈㈤儴涓旇嚧浼ゅ姩鐗╀笉"},{"box":[159,695,231,699,229,725,158,721],"score":0.9842739701271057,"text":"閽堟"},{"box":[280,702,326,702,326,723,280,723],"score":0.9987349510192871,"text":"绗拡"},{"box":[383,704,435,704,435,730,383,730],"score":0.9614325165748596,"text":"绗簩閽?},{"box":[490,709,538,709,538,728,490,728],"score":0.8156992793083191,"text":"绗笁閽?},{"box":[598,709,645,709,645,730,598,730],"score":0.9612410664558411,"text":"绗洓閽?},{"box":[705,711,749,711,749,732,705,732],"score":0.9942670464515686,"text":"绗簲閽?},{"box":[918,707,1492,713,1492,735,918,730],"score":0.9747141599655151,"text":"鑳界‘瀹氬仴搴锋椂锛屽簲褰撶珛鍗冲鐞嗕激鍙ｅ苟娉ㄥ皠鎶楃媯鐘梾鍏嶇柅鐞冭泲鐧斤紝闅忓悗鎺ョ鐙傜姮鐥呯柅鑻椼€?},{"box":[154,725,231,725,231,749,154,749],"score":0.8666267395019531,"text":"鍓傞噺"},{"box":[941,732,41,754],"score":0.956162691116333,"text":"3銆佷娇鐢ㄧ毊璐ㄧ被鍥洪唶鎴栧厤鐤姂鍒跺墏娌荤枟鏃跺彲骞叉壈鎶椾綋浜х敓锛?},{"box":[142,753,241,753,241,772,142,772],"score":0.9806966185569763,"text":"绋嬪簭鎺ョ鏃ユ湡"},{"box":[247,749,330,753,330,777,247,773],"score":0.9749648571014404,"text":"鏈堟棩"},{"box":[358,756,435,756,435,775,358,775],"score":0.9773869514465332,"text":"鏈堟棩"},{"box":[467,754,545,758,543,782,465,779],"score":0.7714246511459351,"text":"鏈?浜烘棩"},{"box":[573,756,652,760,652,780,573,777],"score":0.8127676844596863,"text":"1鏈堬紡鏃?},{"box":[691,763,717,763,717,780,691,780],"score":0.9565006494522095,"text":"鏈?},{"box":[712,763,758,763,758,782,712,782],"score":0.6579834222793579,"text":"浜烘棩"},{"box":[241,773,330,777,330,801,241,798],"score":0.827172577381134,"text":"19鏈?2鏃?},{"box":[943,766,1473,773,1473,796,943,789],"score":0.9515032172203064,"text":"鏈汉宸辩煡鏈鎺ョ浜虹敤鐙傜姮鐥呯柅鑻楀強鐙傜姮鐥呭厤鐤悆铔嬬櫧鐨勭浉鍏充俊鎭紝闂绘剰鎺ョ銆?},{"box":[138,777,241,777,241,796,138,796],"score":0.9062055945396423,"text":"瀹為檯鎺ョ鏃ユ湡"},{"box":[373,782,390,782,390,800,373,800],"score":0.5336645245552063,"text":"鏈?},{"box":[90,784,131,784,131,805,90,805],"score":0.23741930723190308,"text":"蹇笓"},{"box":[410,782,435,782,435,803,410,803],"score":0.9898504018783569,"text":"鏃?},{"box":[479,784,497,784,497,801,479,801],"score":0.9966020584106445,"text":"鏈?},{"box":[526,786,542,786,542,801,526,801],"score":0.9966226816177368,"text":"鏃?},{"box":[582,789,602,782,607,798,588,805],"score":0.9961430430412292,"text":"鏈?},{"box":[632,787,650,787,650,803,632,803],"score":0.9643009305000305,"text":"鏃?},{"box":[696,789,712,789,712,805,696,805],"score":0.9407032132148743,"text":"鏈?},{"box":[741,789,757,789,757,805,741,805],"score":0.9880684018135071,"text":"鏃?},{"box":[948,796,982,796,982,810,948,810],"score":0.8658475875854492,"text":"绛惧瓧锛?},{"box":[156,803,223,803,223,822,156,822],"score":0.8657315373420715,"text":"鐤嫍鎵瑰彿"},{"box":[1094,796,1195,796,1195,815,1094,815],"score":0.9877387881278992,"text":"鎷掔粷鎺ョ绛惧瓧"},{"box":[943,813,1153,817,1153,841,943,838],"score":0.9189605116844177,"text":"鎶楃媯鐘梾鍏嶇柅鐞冭泲鐧界敓浜у巶瀹讹紱"},{"box":[1236,820,1275,820,1275,840,1236,840],"score":0.9892787933349609,"text":"鎵瑰彿锛?},{"box":[239,826,300,826,300,850,239,850],"score":0.5569251775741577,"text":"鍒橀"},{"box":[156,827,222,827,222,846,156,846],"score":0.8828069567680359,"text":"鎶ゅ湡绛惧悕"},{"box":[1382,822,1419,822,1419,843,1382,843],"score":0.9595606327056885,"text":"鍓傞噺锛?},{"box":[947,841,1014,841,1014,860,947,860],"score":0.9276727437973022,"text":"鎺ョ鏃ユ湡锛?},{"box":[1263,840,1368,843,1368,867,1263,864],"score":0.9495972394943237,"text":"鎺ョ浜哄憳绛惧悕锛?},{"box":[131,852,405,859,405,881,131,874],"score":0.9359565377235413,"text":"*璇锋偍鎸夌収浠ヤ笂瑙勫畾鐨勬椂闂存寜鏃舵帴绉嶇柅鑻椼€?},{"box":[943,862,1277,866,1277,890,943,886],"score":0.9533369541168213,"text":"浠ヤ笂鍛婄煡鍐呭鏈汉宸茬粡璇︾粏闃呰锛屽悓鎰忓尰甯堝缓璁€?},{"box":[1242,890,1338,881,1341,926,1245,935],"score":0.36582446098327637,"text":"涓囨€婚櫌"},{"box":[948,897,1213,904,1213,932,948,925],"score":0.8303040266036987,"text":"鍙楃鑰咃紙鎴栫洃鎶や汉锛夌瀛楋細闄堝伐"},{"box":[1382,888,1649,878,1654,973,1387,984],"score":0.8897692561149597,"text":"鏇剧嚂鐝?},{"box":[215,899,698,909,698,932,215,921],"score":0.96095871925354,"text":"浜虹敤鐙傜姮鐥呯柅鑻楀拰鎶楃媯鐘梾鍏嶇柅鐞冭泲鐧芥帴绉嶇煡鎯呭悓鎰忎功"},{"box":[126,932,799,946,799,970,126,956],"score":0.9663658142089844,"text":"銆愮柧鐥呯畝浠嬨€戠媯鐘梾鏄敱鐙傜姮鐥呯梾姣掑紩璧风殑鎬ユ€т紶鏌撶梾锛屼富瑕佺敱鎼哄甫鐙傜姮鐥呮瘨鐨勭姮锛岀尗绛夊姩鐗╄嚧浼ゅ紩璧枫€?},{"box":[968,940,1059,940,1059,968,968,968],"score":0.9395599365234375,"text":"鍖诲笀绛惧锛?},{"box":[1435,953,1453,958,1448,979,1430,973],"score":0.49177226424217224,"text":"A"},{"box":[95,958,774,972,774,996,95,982],"score":0.9456110596656799,"text":"褰撲汉琚劅鏌撶媯鐘梾姣掔殑鍔ㄧ墿鍜激銆佹姄浼ゅ強鑸斿埌浼ゅ彛鎴栫矘鑶滃悗锛屽叾鐫℃恫鎵€鍚梾姣掔粡浼ゅ彛鎴栫矘鑶滆繘鍏ヤ汉浣擄紝"},{"box":[95,989,300,989,300,1012,95,1012],"score":0.8878030776977539,"text":"涓斿紩璧峰彂鐥咃紝鐥呮鐜囪揪100%銆?},{"box":[1258,987,1382,987,1382,1006,1258,1006],"score":0.9348161220550537,"text":"鎺ョ鍗曚綅锛堢洊绔狅級锛?},{"box":[120,1013,801,1029,801,1053,120,1038],"score":0.9629994034767151,"text":"琚彲鐤戝姩鐗╁挰浼ゅ悗锛屽簲绔嬪嵆姝ｇ‘澶勭悊浼ゅ彛锛屾牴鎹渶瑕佹敞灏勬姉鐙傜姮鐥呰娓?鐙傜姮鐥呬汉鍏嶇柅鐞冭泲鐧藉拰涓ユ牸鎸?},{"box":[1307,1019,1377,1019,1377,1038,1307,1038],"score":0.3012849986553192,"text":"w"},{"box":[1398,1020,1407,1020,1407,1029,1398,1029],"score":0.5249418020248413,"text":"2"},{"box":[1409,1017,1448,1017,1448,1036,1409,1036],"score":0.32993289828300476,"text":"1"},{"box":[85,1038,796,1053,796,1081,85,1066],"score":0.9605026245117188,"text":"鐓ц姹傚叏绋嬫帴绉嶇媯鐘梾鐤弻锛屽垯鑳藉ぇ澶у噺灏戝彂鐥呯殑椋庨櫓銆傛姉鐙傜姮鐥呭厤鐤悆铔嬬櫧鍜屼弗鏍兼寜鐓ц姹傚叏绋嬫帴绉嶇媯"},{"box":[1290,1040,1332,1040,1332,1059,1290,1059],"score":0.7153218388557434,"text":"鏃ユ湡锛?},{"box":[1368,1041,1387,1041,1387,1057,1368,1057],"score":0.9995852112770081,"text":"骞?},{"box":[1403,1038,1466,1038,1466,1062,1403,1062],"score":0.9165599346160889,"text":"鏈堟棩"},{"box":[83,1066,796,1080,796,1109,83,1095],"score":0.9363241791725159,"text":"鐘柅鑻椼€傚垯鑳藉ぇ澶у噺灏戝彂鐥呴闄┿€傛姉鐙傜姮鐥呭厤鐤悆铔嬬櫧鑳界壒寮傚湴涓拰鐙傜姮鐥呯梾姣掞紝鍙枃鍗宠捣鏁堛€傜媯鐘柅鑻?},{"box":[81,1092,785,1107,785,1137,81,1121],"score":0.9572349786758423,"text":"鎺ョ鍚庡彲鍒烘縺鏈轰綋浜х敓鎶楃媯鐘梾姣掔殑淇濇姢鎬ф姉浣撱€備负瀹夊叏鏈夋晥鍦颁娇鐢ㄧ媯鐘梾鐤嫍鍜屾姉鐙傜姮鐥呭厤鐤悆铔嬬櫧锛?},{"box":[920,1085,1185,1086,1185,1106,920,1104],"score":0.9182799458503723,"text":"鍜ㄨ鐢佃瘽027-87159100027-87399709"},{"box":[79,1121,650,1132,650,1161,79,1151],"score":0.9600839614868164,"text":"鍦ㄦ偍浣跨敤涔嬪墠鎴戜滑灏嗘湁鍏充俊鎭憡鐭ヤ簬鎮紝鎮ㄥ彲浠ユ牴鎹嚜宸辩殑鍏蜂綋鎯呭喌鍐冲畾鏄惁浣跨敤銆?},{"box":[934,1121,1414,1125,1414,1149,934,1146],"score":0.8979658484458923,"text":"鏈煡鎯呭悓鎰忎功涓€寮忎袱浠斤紙鍙楃鑰呭拰鎺ョ鍗曚綅鍚勬寔1浠斤級锛岃濡ュ杽淇濈2骞?}]}
OCR exit.
Press any key to continue . . . 1329,733,1329,756,9],

为什么我的vb返回的是乱码

**Comment by hiroi-sora** [comment]
你好，建议使用刚刚更新的 v1.2.1 版，并参考[详细使用指南](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/docs/%E8%AF%A6%E7%BB%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md#0-%E5%85%B3%E4%BA%8Edebug%E6%A8%A1%E5%BC%8F) 关闭debug模式，这样可以输出utf-8编码的纯ascii json字符串，规避乱码问题。

**Comment by hiroi-sora** [comment]
> 能不能设计一个参数发送图片数据base64格式。

我也在考虑这个问题，但是主要担心管道传大量数据时，因为某些原因读取速度小于输入速度，导致爆缓冲区，丢失一些字节。

纯内存传图片，你可以暂时用v1.2.1的剪贴板功能，这是比较安全的。

**Comment by xxdoc** [comment]
很奇怪。我用1.21也是乱码。我在CMD中直接使用正常的，但是如果我用管道写入dir也是可以返回中文的。但是如果写入你这个就返回的中文乱码。我是用readfile来读取的数据。

**Comment by hiroi-sora** [comment]
有没有传入启动参数  -use_debug=0

**Comment by xxdoc** [comment]
可以一起传送吗。PaddleOCR_json.exe --use_debug=0  --image_dir=“xxx.jpg”

**Comment by hiroi-sora** [comment]
启动参数可以叠加。
不过启动参数传入的图片路径不能含中文，而且每次就识别一张图片，重复调用会浪费初始化的时间。建议图片路径还是通过管道json传入比较好。

**Comment by xxdoc** [comment]
有没有退出的命令。我发现执行了后没有退出，我需要返回去执行其他dos命令

**Comment by hiroi-sora** [comment]
> 有没有退出的命令

木有，直接kill掉进程即可

**Comment by xxdoc** [comment]
哦。能不能搞一个空白的控制台程序。就是以你目前程序返回的编码方式写的。。只需要返回一个中文英文混合即可。比喻说执行test.exe 返回 测试test123  我怀疑我写管道程序读取的时候又自动转码了。我想看看能不能重新写个自己转码。

**Comment by xxdoc** [comment]
你的这个比onenote识别强太多。可以媲美GitHub中的熊猫识别了。

**Comment by hiroi-sora** [comment]
你代码设置 -use_debug=0 ，随便传入一个路径，读取后先不要json反序列化（从字符串转成对象或字典），直接打印原始字符串，看看是啥？是不是纯英文+数字，没有乱码？
如果此时也有乱码，那就是引擎没收到 -use_debug=0 没有解除debug模式。

然后再json反序列化，看看转的结果是啥？
如果此时也有乱码，那就是你反序列器的锅。

**Comment by xxdoc** [comment]
关闭管道，程序居然还是关闭不了。非要关闭本进程才行。如果搞个命令能退出就好了。

**Comment by hiroi-sora** [comment]
销毁管道可能是不能结束子进程的，请用kill干掉它。

创建管道的时候有拿到进程对象吗？有的话就用 [process.kill](https://learn.microsoft.com/zh-cn/dotnet/api/system.diagnostics.process.kill?view=net-6.0) 。没有的话，用 [Process.GetProcessById](https://learn.microsoft.com/zh-cn/dotnet/api/system.diagnostics.process.getprocessbyid?view=net-6.0) 去拿一下。

通过程序命令退出，主要是存在延迟，不能异步，必须等本轮任务结束才能处理下一轮命令。而调用方直接kill掉子进程是简洁高效，

**Comment by xxdoc** [comment]
作者你好。我用vb调用的时候，有个国外网友说你用了短路径，在win10会导致默认程序名和配置名会导致调用失败。

**Comment by hiroi-sora** [comment]
> 我用vb调用的时候，有个国外网友说你用了短路径，在win10会导致默认程序名和配置名会导致调用失败。

如果你指的是DOS命名规则那个`~1`后缀的**短路径**，在本项目能触及到的范围内没有使用。

如果你指的是Opencv中`GetModuleFileName()`函数，win7以上系统它拿到的是全路径。

如果你指的是**相对路径**，引擎所有地址既可以传入相对也可以传入绝对路径，你用不了相对的话传绝对路径就行了。

**Comment by xxdoc** [comment]
Edit: Now I see it's using exe_name = google::ProgramInvocationShortName() which can be problematic if your exe name is PaddleOCR_json.exe as short name is PADDLE~1.EXE so your config file should be in PADDLE~1_config.txt which is unexpected.

**Comment by hiroi-sora** [comment]
我明白他意思了，`google::ProgramInvocationShortName()` 其实相当于 `basename(argv[0])` ，可能在早期win系统或者linux里 `argv[0]` 是 `~1` 后缀的短路径。但是在win7、win10环境下，取到都是正常的完整路径，至少我没见过从argv0里取到短路径的。

想完全避免这个潜在问题的话，采用传入指定配置文件的方式咯。
