### ISSUE TITLE
[PP OCR v4] Can't work correctly when update paddle model to v4

### ISSUE THREAD

**Issue by quangnv13** [hiroi-sora/PaddleOCR-json#160]
Currently I've an issue related to chinese simplified text dection with some characters. I was think it can increase the accuracy when update model of paddle chinese model from v3 to v4.

I've downloaded the v4 model from paddleocr and put them in the models directory in this library. And then create a config_chinese_v4.txt file.
![image](https://github.com/user-attachments/assets/90be37ac-af47-4af3-a271-803a4d05cdcb)

UmiOCR select model
![image](https://github.com/user-attachments/assets/2326f64c-bff7-475e-b6b1-7e56ea79857b)

Load it in to UmiOCR and then the result of
![image](https://github.com/user-attachments/assets/4daf18db-fd9b-4092-899b-f44894807bcc)

is a messed text even we only have 5 words there.
![image](https://github.com/user-attachments/assets/cbe06306-0190-470d-9723-6a4234a21505)

With v3 model the result is, you can see it can't detect the first word **下**
![image](https://github.com/user-attachments/assets/f40e7451-7757-4469-b271-8992dca5bf4b)

Can we update to v4 or can we let it more accuracy? Thanks.

**Comment by hiroi-sora** [comment]
The stable version of this project is based on version `v2.3.2` of the Paddle Inference engine. This version is more stable and efficient on most CPUs but does not support the v4 model.

If you want to use the v4 model, you have two options:

1. Use [PaddleOCR-json v1.4.1 dev](https://github.com/hiroi-sora/PaddleOCR-json/releases/tag/v1.4.1-dev). This beta version is based on version `3.0.0 beta-1` of Paddle Inference and fully supports the v4 model. However, it is not as efficient on low to mid-range home CPUs as previous versions.

2. Use [RapidOCR-json](https://github.com/hiroi-sora/RapidOCR-json). This project supports and includes the v4 model by default and has good CPU compatibility.

**Comment by quangnv13** [comment]
> The stable version of this project is based on version `v2.3.2`of the Paddle Inference engine. This version is more stable and efficient on most CPUs but does not support the v4 model.
> 
> If you want to use the v4 model, you have two options:
> 
> 1. Use [PaddleOCR-json v1.4.1 dev](https://github.com/hiroi-sora/PaddleOCR-json/releases/tag/v1.4.1-dev) . This beta version is based on version `3.0.0 beta-1`of Paddle Inference and fully supports the v4 model. However, it is not as efficient on low to mid-range home CPUs as previous versions.
> 2. Use [RapidOCR-json](https://github.com/hiroi-sora/RapidOCR-json) . This project supports and includes the v4 model by default and has good CPU compatibility.

Great, thank you! I think I'll use the first approach. And you might can split the code to some separates branch eg non-AVX512 cpu and AVX512 cpu. Why I choose the first because I think paddle ocr is more popular and have tested by many people and I don't need the response fast(I need accuracy).

By the way. Did you check my example in the image attached? Can you detect full 5 words? I've trying easy-ocr with default trained data and it can detect full(but most other case its accuracy is not good) :)

**Comment by hiroi-sora** [comment]
> Did you check my example in the image attached? Can you detect full 5 words?

When using the v3 model, it was not possible to detect 5 characters from the original image. This is because the Chinese characters in the image are slightly incomplete (partially obscured at the bottom), and the spacing between characters is wide, with large pixel sizes (differing from the training data). These factors affect the accuracy of recognition. If the image is preprocessed by reducing its size and appropriately increasing the margins, it can recognize 5 characters.
﻿
When using the v4 model, the accuracy improves, and it can correctly recognize all characters from the original image.
﻿
As shown below, the first result is v3 + original image, the second result is v3 + processed image, and the third to last results are v4 + original image.
﻿
![image](https://github.com/user-attachments/assets/31a96090-472f-4915-b2e4-e1b9447076c6)

**Comment by quangnv13** [comment]
> > Did you check my example in the image attached? Can you detect full 5 words?
> 
> When using the v3 model, it was not possible to detect 5 characters from the original image. This is because the Chinese characters in the image are slightly incomplete (partially obscured at the bottom), and the spacing between characters is wide, with large pixel sizes (differing from the training data). These factors affect the accuracy of recognition. If the image is preprocessed by reducing its size and appropriately increasing the margins, it can recognize 5 characters. ﻿ When using the v4 model, the accuracy improves, and it can correctly recognize all characters from the original image. ﻿ As shown below, the first result is v3 + original image, the second result is v3 + processed image, and the third to last results are v4 + original image. ﻿ ![image](https://private-user-images.githubusercontent.com/56373419/386831444-31a96090-472f-4915-b2e4-e1b9447076c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTk3MTMsIm5iZiI6MTczMTgxOTQxMywicGF0aCI6Ii81NjM3MzQxOS8zODY4MzE0NDQtMzFhOTYwOTAtNDcyZi00OTE1LWIyZTQtZTFiOTQ0NzA3NmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA0NTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NzViM2M0ZWYwMWE0MjhlNmExNGY0NDdhMTI2M2Y2MGNhZmE1MTlkYmRhZTFiMmI5NjBmZjljNjJhZTcyZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P1E7dvEPpPowe08wam3e8_QjdRbBhUhDkqxIMS7gzxw)

Thank you now I understand but just concerned about "preprocessed by reducing its size and appropriately increasing the margins" does it cost will equal or larger than using v4 model(which will decrease perfomance sligtly for non-AVX512 cpu) or not. If my purpose is only detect chinese character in high performance and modern computer for gamming, could you please recommend me which is the best approach?

**Comment by quangnv13** [comment]
I think I'll choose v4 model for more accurate cause I need it. So will close this issue. Thanks @hiroi-sora for your support
