### ISSUE TITLE
可以添加c++支持推理使用sast模型吗？

### ISSUE THREAD

**Issue by llooper-dev** [hiroi-sora/PaddleOCR-json#2]
![image](https://user-images.githubusercontent.com/65935005/161378507-a392d850-084b-4150-82a3-9003be0fd40f.png)
大佬，可以添加c++推理调用sast模型吗？我这里训练出SAST高精度模型，但只能应用python上。是否可以支持？可以交流下吗？有偿也可以

**Comment by hiroi-sora** [comment]
抱歉呢，暂时没有支持更多模型的计划。

目测c++改起来也并不容易……
