### ISSUE TITLE
图片过小导致识别乱码,(对于中文)

### ISSUE THREAD

**Issue by PunchlY** [hiroi-sora/PaddleOCR-json#22]
控制面板 -> 6Rb?g

![image](https://user-images.githubusercontent.com/100825215/195905319-13e14daf-ecd5-47ce-94eb-7fe03b3e4d61.png)
![MouseInc 012123](https://user-images.githubusercontent.com/100825215/195905234-f12a8559-925b-46ba-b880-25247c92c90e.png)

**Comment by hiroi-sora** [comment]
此事处处透露着诡异🤣

1. 小图片识别率**低**是1.2版本的bug，1.3应该已经改了
2. 就算识别率**低**，也不可能在**乱码**中出现`▯`符号，因为[字典中根本没有它](https://github.com/hiroi-sora/Umi-OCR/blob/main/PaddleOCR-json/ppocr_keys_v1.txt)
3. 我测试这张图似乎没问题：

![image](https://user-images.githubusercontent.com/56373419/195962280-ab0d66a2-199a-48ff-989b-4e219f995eff.png)

综上，我倾向于是**编码**出了问题。推测，你是不是写API用的v1.3的规则，但引擎exe还是用的1.2；所以1.2识别小图不准，输出字符串又被API错误编码最后变成了乱码？
