### ISSUE TITLE
可视化结果图片未生成

### ISSUE THREAD

**Issue by alexlausz** [hiroi-sora/PaddleOCR-json#28]
版本： PaddleOCR-json.v1.2.1
运行环境：win11

调用方法如图所示：
![微信图片_20221103092725](https://user-images.githubusercontent.com/32123947/199632732-f60a13f4-98d1-480f-950b-ce1173c28c7f.jpg)

OCR识别正常，但在指定的输出目录中没看到结果图片
output_dir 的值试过 'D:/temp/ocr_output'  和 'D:\\temp\\ocr_output' ，一样没看到图片。

请帮忙看看哪里操作有问题，谢谢。

**Comment by hiroi-sora** [comment]
图片名是不是中文？可视化功能跟OCR流程不同，我用的还是opencv标准api，未改用wstring支持，所以对非ascii码支持不是很好。图片名改成全英文试试。

设计上，这个功能主要用于开发调试。如果想展示给用户看，根据OCR结果自己在前端绘制更好。

**Comment by alexlausz** [comment]
> 图片名是不是中文？可视化功能跟OCR流程不同，我用的还是opencv标准api，未改用wstring，所以对非ascii码支持不是很好。图片名改成全英文试试。
> 
> 设计上，这个功能主要用于开发调试。如果想展示给用户看，根据OCR结果自己在前端绘制更好。

感谢回复。

我的图片路径是：testImg = r'D:\test_data\samples\hktw.png'
这些图片我用opencv可以正常读取、修改和保存。

我的自动化脚本会用到文字坐标，所以有时会去看下文字框，如果PPOCR直接可以输出就比较方便。

**Comment by hiroi-sora** [comment]
就是还没解决吗？那我再调查一下。

**Comment by hiroi-sora** [comment]
我更新了Python API，添加了一个python实现的可视化模块，不依赖引擎自身功能。

https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python

**Comment by alexlausz** [comment]
> 我更新了Python API，添加了一个python实现的可视化模块，不依赖引擎自身功能。支持中文路径和自定义各种输出图层。
> 
> https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python

更新后有结果图片了，赞！
