### ISSUE TITLE
call PaddleOCR_json -use_debug=0 -image_dir="D:\\ocr.bmp"  > 123.txt

### ISSUE THREAD

**Issue by icyfox168168** [hiroi-sora/PaddleOCR-json#29]
use_debug=1 就正常

现在文本都不是可视字符了

PaddleOCR-json v1.2.1
OCR init completed.
{"code":100,"data":[{"box":[[384,6],[403,6],[403,23],[384,23]],"score":0.8491007089614868,"text":"\u53e3"},{"box":[[28,8],[121,8],[121,22],[28,22]],"score":0.9404433369636536,"text":"\u8ff7\u96fe\u901a4.4.20"},{"box":[[443,6],[462,6],[462,23],[443,23]],"score":0.7332991361618042,"text":"X"},{"box":[[35,69],[54,69],[54,90],[35,90]],"score":0.27678585052490234,"text":"8"},{"box":[[287,69],[310,69],[310,91],[287,91]],"score":0.6947178840637207,"text":"C"},{"box":[[99,71],[162,71],[162,92],[99,92]],"score":0.9988619685173035,"text":"icyfox"},{"box":[[371,69],[411,69],[411,92],[371,92]],"score":0.994987964630127,"text":"\u767b\u51fa"},{"box":[[99,131],[222,131],[222,151],[99,151]],"score":0.9241697788238525,"text":"\u4eab\u53d7\u65e0\u9650\u901f\u5ea6"},{"box":[[342,130],[422,132],[422,153],[342,151]],"score":0.8816037178039551,"text":"\u9a6c\u4e0a\u8d2d\u4e70\uff01"},{"box":[[231,319],[350,319],[350,347],[231,347]],"score":0.9966230988502502,"text":"\u8fde\u63a5\u6210\u529f"},{"box":[[231,356],[392,356],[392,374],[231,374]],"score":0.8895745277404785,"text":"0.00k274ms0.0%"},{"box":[[152,400],[198,400],[198,447],[152,447]],"score":0.9788767695426941,"text":"+"},{"box":[[212,408],[348,408],[348,435],[212,435]],"score":0.9950642585754395,"text":"\u745e\u58eb/\u82cf\u9ece\u4e16"},{"box":[[149,462],[333,462],[333,479],[149,479]],"score":0.9467524886131287,"text":"ch-zrh-01.exits.geph.io"},{"box":[[196,655],[287,655],[287,679],[196,679]],"score":0.9990895986557007,"text":"\u66f4\u6539\u4f4d\u7f6e"},{"box":[[217,721],[266,721],[266,749],[217,749]],"score":0.9995450973510742,"text":"\u65ad\u5f00"},{"box":[[388,814],[417,814],[417,841],[388,841]],"score":0.327283650636673,"text":"*"},{"box":[[61,840],[101,842],[100,865],[60,863]],"score":0.9298021197319031,"text":"\u6982\u89c8"},{"box":[[226,845],[259,845],[259,862],[226,862]],"score":0.893752932548523,"text":"\u901a\u77e5"},{"box":[[388,845],[419,845],[419,861],[388,861]],"score":0.9994618892669678,"text":"\u8bbe\u7f6e"}]}
OCR exit.

**Comment by hiroi-sora** [comment]
是滴，设计就是这样，请再看看 [详细使用指南](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/docs/%E8%AF%A6%E7%BB%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md#0-%E5%85%B3%E4%BA%8Edebug%E6%A8%A1%E5%BC%8F)

debug模式直接输出utf-8中文字符是为了方便调试观察。非debug模式下则输出**经过转义**的\u前缀ascii码，便于调用方接收和处理，可以避免很多编码转换问题。

随便一个json解析库，应该都支持ascii反转义，就是把这串东西变回可读的中文字符。调用方把它json转对象/字典就可以读了。

**Comment by icyfox168168** [comment]
原来这样

还有一个问题，我按照你cmake方法编译成功了

这个地方的连接怎么样确保是最新的

我对比编译出来的dll还没你自带的121版本新

FetchContent_Declare(
    paddle
    URL https://paddle-wheel.bj.bcebos.com/develop/win-infer/mkl/cpu/paddle_inference.zip
    URL_HASH MD5=b20e33128938d69bca106d49f6336c5c
    DOWNLOAD_EXTRACT_TIMESTAMP ON
)

**Comment by hiroi-sora** [comment]
估计是PPOCR C++预测库（paddle_inference.zip）的版本不同。

本项目1.2.1 Release版本是根据paddle官方文档 [手动构建](https://github.com/hiroi-sora/PaddleOCR-json/blob/main_old_builds/docs/%E9%A1%B9%E7%9B%AE%E6%9E%84%E5%BB%BA%E6%8C%87%E5%8D%97.md) 的，cmake则是后来 @ruitard 贡献，cmake里的URL可能跟我当时用的不一样。

我所用的paddle_inference的版本文件（version.txt）是：
```
GIT COMMIT ID: 4596b9a22540fb0ea5d369c3c804544de61d03d0
......
CXX compiler version: 19.16.27045.0
```

不过就算不同应该也影响不大，PPOCR-V3模型库发布以来没啥重大更新，有更新也是表格识别那块的，跟本项目无关。

**Comment by icyfox168168** [comment]
可以提供DLL导出函数的版本？ 这样更方便点

**Comment by ruitard** [comment]
> 估计是PPOCR C++预测库（paddle_inference.zip）的版本不同。
> 
> 本项目1.2.1 Release版本是根据paddle官方文档 [手动构建](https://github.com/hiroi-sora/PaddleOCR-json/blob/main_old_builds/docs/%E9%A1%B9%E7%9B%AE%E6%9E%84%E5%BB%BA%E6%8C%87%E5%8D%97.md) 的，cmake则是后来 @ruitard 贡献，cmake里的URL可能跟我当时用的不一样。
> 

是的，我当时没注意，用的版本比较旧，还是 v2.1 的版本。应该用这个 `https://paddle-inference-lib.bj.bcebos.com/2.3.2/cxx_c/Windows/CPU/x86-64_avx-mkl-vs2017/paddle_inference.zip`

**Comment by icyfox168168** [comment]
这是我的生成脚本

可以把配置文件和那些特征文件打包不

这样生成就和你发布版本差不多了
D:\Users\fix\Documents\GitHub\vcpkg\vcpkg install opencv:fix64-windows

D:\Users\fix\Documents\GitHub\vcpkg\vcpkg install dirent:fix64-windows

D:\Users\fix\Documents\GitHub\vcpkg\vcpkg install nlohmann-json:fix64-windows

D:\Users\fix\Documents\GitHub\vcpkg\vcpkg install glog:fix64-windows

D:\Users\fix\Documents\GitHub\vcpkg\vcpkg install gflags:fix64-windows

cd D:\Users\fix\Documents\GitHub\PaddleOCR-json\project_files\cpp_infer

cmake -B build -DCMAKE_BUILD_TYPE=Release -DMSVC_RUNTIME=static -DCMAKE_TOOLCHAIN_FILE=D:/Users/fix/Documents/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake .

cmake --build build --config Release --target install

cmake --build build --config Release --target package
pause

**Comment by icyfox168168** [comment]
有没调试命令显示图片出来，然后框出来text的地方，

我给的图片并没这个口

我想看看程序识别哪个地方了

{"code":100,"data":[{"box":[[384,6],[403,6],[403,23],[384,23]],"score":0.8491007089614868,"text":"口"}

其他很准确，没啥问题

**Comment by hiroi-sora** [comment]
> 显示图片出来，然后框出来text的地方

引擎自带可视化输出功能，传 `--visualize=1` 启用，见 [动态参数](https://github.com/hiroi-sora/PaddleOCR-json#%E5%8A%A8%E6%80%81%E5%8F%82%E6%95%B0)
但它有点小问题，比如不支持中文名称的图片。

如果你用Python，建议用 [Python API 的可视化模块](https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python#%E7%BB%93%E6%9E%9C%E5%8F%AF%E8%A7%86%E5%8C%96) ，更稳定，功能更强大。

**Comment by ruitard** [comment]
> 可以提供DLL导出函数的版本？ 这样更方便点

我倒是正在开发一个，已经封装成库了（目前是静态库），稍微改一下就可以编译出动态库了
> https://github.com/ruitard/PaddleOCR-deployA
