### ISSUE TITLE
请问作者有交流群吗

### ISSUE THREAD

**Issue by GithubMonsterZ** [hiroi-sora/PaddleOCR-json#3]
有些问题想请教一下。
1.1如果用cmake软件编译
我在编译paddleocr的过程中，发现作者自定义的include文件夹下，并没有包含config.h。
并且还有其它一些微小的错误。

1.2如果用vs2019中的cmake编译，则会由于无法添加paddle的include文件目录，导致paddle_api.h不能正确导入，也会导致编译失败。

2.请问作者在程序中，是否使用了gpu？
如果使用了gpu，那我应该在CUDA_LIB以及CUDNN_LIB填写什么项的地址。

本人工程经验太少，希望各位大神能帮帮小弟解惑。

**Comment by hiroi-sora** [comment]
没有交流群哈，我只是一个小小的个人开发者~

1. 本工程是在PaddleOCR官方demo的基础上修改而成，因此只上传了“有修改过”的文件。若你本地demo工程存在某些文件而本项目中没有，说明本项目未修改该文件，不理它即可。
- 因此，本项目的正确打开方式是：先将官方demo编译、跑起来，**确认没问题**；再将本项目的代码替换进去。甚至，为了保证编码一致，建议替换文本而不是整个文件。
- 倒不如说，配环境、编译到能跑起来，才是最难的一步。后续修改代码反而没啥技术含量了🤣

3. 未使用GPU~ 个人感觉cpu的速度已经能满足所需（不比在线ocr慢），就懒得趟gpu这更大的坑了

对了，工程跑起来后还有以下要点（适用于vs2019）：
- 工程设为Release模式而不是debug模式。
- 工程设为全局utf-8编码。若遇到乱码问题，有些教程建议将字典文件设为gbk编码来避免，这是错误的做法。必须保证输出是utf-8，否则部分特殊字符会导致程序崩溃。
- 留意注释，中文注释可能导致cmake编译错误，保险起见结尾都加个空格来隔开换行符。
- 留意收集齐所需的dll，以免你的程序移到别的电脑无法使用。可以建个沙盒来测试缺了哪些dll。而且，虽然程序是64位的，但有些dll是x64而有些要求x86，可能要一个一个试同名文件。

希望能帮到你！
