### ISSUE TITLE
Linux下是否可以正常编译

### ISSUE THREAD

**Issue by Wang-Zhenxing** [hiroi-sora/PaddleOCR-json#31]
你好，请问在Linux（Ubuntu20.04）环境下是否可以正常编译打包？谢谢！

**Comment by hiroi-sora** [comment]
暂不支持。一方面，构建工程需要引入部分opencv和paddle编译好的win平台dll。另一方面，代码中unicode、剪贴板等处理依赖windows api。
当然PPOCR本身支持Linux，本项目未来可能考虑移植。

**Comment by 204winnersong** [comment]
Linux环境部署的移植的是否有计划安排？

**Comment by hiroi-sora** [comment]
> Linux环境部署的移植的是否有计划安排？

优先级不高，短期内没有计划。
