### ISSUE TITLE
批处理脚本如图调用时第一次乱码

### ISSUE THREAD

**Issue by Golden-nianhua** [hiroi-sora/PaddleOCR-json#32]
![Snipaste_2022-12-26_14-55-48](https://user-images.githubusercontent.com/66005333/209514974-227e31de-a597-4688-9aaa-2cbe2af0d1bb.png)
![Snipaste_2022-12-26_14-57-51](https://user-images.githubusercontent.com/66005333/209514989-4b59bc9b-9786-471c-900e-d6c803bb17fa.png)
win10 v1.2.1
如图片方式调用时，第一次会乱码，之后调用没有问题
希望批处理调用时能传入多个图片路径，或者取消输出后的Press any key to continue

**Comment by hiroi-sora** [comment]
> 调用时，第一次会乱码，之后调用没有问题

1. 原则上建议开启 **ensure_ascii** `转ascii编码` 来彻底避免编码乱码问题。但调用方就需要多做一步，重新将ascii字母转回中文字符。
2. 按你说后续调用时就没有问题了，这我还真不清楚原因。“后续调用”是指什么情况？同一次运行脚本的第二条输出？还是第二次运行脚本？

> 希望批处理调用时能传入多个图片路径

由于设计上遵守一进一出，所以每行输入只会产生一行输出。暂时没有计划让一次命令执行多个任务。

> 取消输出后的Press any key to continue

可以的，**use_system_pause**。

详情请阅读 [详细使用指南](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/docs/%E8%AF%A6%E7%BB%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md)。

**Comment by Golden-nianhua** [comment]
谢谢
后续是指在同一个cmd.exe中，用for调用第一次乱码之后，以后用for就不会乱码
然后我又去试了一下，只要是夹在for命令里，参数都无效了
不知道这个东西啥情况，我尽量不放到for命令里面就好

**Comment by Golden-nianhua** [comment]
刚忽然想起来，等号前面加一个取消转译^就好了，虽然我也不知道具体的意义，之前只用过一次，我的问题抱歉了www

**Comment by Golden-nianhua** [comment]
谢谢
后续调用是指在同一个cmd.exe中，第一次调用完乱码以后，之后就不会有问题，同一次运行脚本的第二条输出
不放到for里也没问题，就很奇怪
