### ISSUE TITLE
识别结果如何合并成完整的文本呢?

### ISSUE THREAD

**Issue by z284949127** [hiroi-sora/PaddleOCR-json#33]
识别结果如何合并成完整的文本呢? 我用的是java,返回了很多box, 但是我想把他合并成一整段文本

**Comment by hiroi-sora** [comment]
首先得把返回结果的json字符串转换为java类（对象），通过其中的`code`属性判断执行成功与否，然后通过`data`属性提取数据。成功情况下`data`是一个数组，可以遍历它，累加每一项的`text`属性来拼凑完整文本。
