### ISSUE TITLE
PaddleOCR_json 跑一段时间后，服务异常，返回null值，不知道如何解决

### ISSUE THREAD

**Issue by 204winnersong** [hiroi-sora/PaddleOCR-json#34]
PaddleOCR_json 跑一段时间后，服务异常，返回null值，不知道如何解决？
![image](https://user-images.githubusercontent.com/73173024/212841051-22d2729d-925a-442b-bd2e-9dda71062680.png)

**Comment by hiroi-sora** [comment]
请问“返回null值”是指返回返回什么都没有的空行吗？

有什么固定规律，比如使用多长时间后出现问题，对某张图片出现问题？

从你的截图上来看，数值似乎是正常的。
