### ISSUE TITLE
识别器执行后会输出加载内容， 不知道通过什么参数关闭它

### ISSUE THREAD

**Issue by lgl8023** [hiroi-sora/PaddleOCR-json#36]
![image](https://user-images.githubusercontent.com/54259926/216270934-32c7fb08-9898-440e-8521-dd176bb4c8a5.png)

**Comment by hiroi-sora** [comment]
1. 这是上游项目 [PaddleOCR v2.6 C++](https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6) 的一个bug，加载运行库的过程中会强制输出日志信息，无法用外部手段关闭。我给源项目提过 [issue](https://github.com/PaddlePaddle/PaddleOCR/issues/7393) ，维护者说将在下个版本修复，届时本项目也会跟进更新。
2. 这个bug不会影响实际使用。因为日志信息输出在 **stderr** 流，但你的调用方程序只需要监听 PaddleOCR-json.exe 的 **stdout** 流。也就是日志信息只会被你肉眼观察到，不会被调用方程序接收到。
