### ISSUE TITLE
创建的进程似乎必须手动kill掉

### ISSUE THREAD

**Issue by TheBlueSkim** [hiroi-sora/PaddleOCR-json#37]
我是php，使用proc_open创建的进程，发现proc_close并不能实际关闭paddleocr进程，proc_terminate也不能关闭，必须通过proc_get_status获取到pid，然后手动执行taskkill /F /T /PID ***才可以。

是原始设计就需要这么做吗？还是我的姿势不对啊

**Comment by hiroi-sora** [comment]
是的，原始设计就是需要调用方主动kill掉引擎进程。

至于php我不了解，抱歉。
