### ISSUE TITLE
【Bug】退出前暂停程序参数（use_system_pause）在单独使用时不生效

### ISSUE THREAD

**Issue by sls463** [hiroi-sora/PaddleOCR-json#38]
我在Win10平台CMD窗口下执行CLI命令运行到"退出前暂停程序"这一步骤时窗口会显示"Press any key to continue . . .", 但如果想采用DOS重定向符方式生成文本文件 (即 >xxx.txt )，那么这一句话就不会在窗口显示，而是输出到 xxx.txt 中了，这时候看CMD窗口会让人很懵B，由于没有显示那句话，看上去像是还在运行中，或者是卡死了，我又查看了 xxx.txt 的文件大小显示为0，结果我傻等了好一会见还是没动静只好选择点Esc或中断键放弃，这时候发现 xxx.txt 文件生成成功了(也就是大小已经不是0了)，实际是由于按了任意键，所以退出了暂停状态，搞了大半天我才明白这是怎么一回事。

为了解决以上问题，我到Issues查看了一下，发现作者回复其他问题时有提到过 -use_system_pause (退出前暂停程序) 说这一参数可以关闭，我尝试了一下(例如: PaddleOCR_json.exe -use_system_pause=0 -image_dir="D:\OCR.jpeg")，发现没有用，依然会“退出前暂停程序”。

我又查看了"详细使用说明", 以我的理解总结为，PaddleOCR_json.exe 支持的CLI命令格式只有两个参数 -use_debug、-image_dir ，而其它在说明中提到的参数都是属于 -use_debug= 的子参数，是不能单独拿出来用的，我尝试了一下(例如: PaddleOCR_json.exe -use_debug=0 -image_dir="D:\OCR.jpeg")，确实关闭了"退出前暂停程序"，但又出现了新的问题，文本内容不是能直接采用的明文了，而是转成了转ASCII编码(\u前缀格式 好像正确应该是叫Unicode 统一码/万国码)，还是再另想办法转回明文，汗!!!

我觉得"退出前暂停程序"这一步骤真的有点多余，如果能取消的最好，如果不能，那么能不能把它从子参数中提出来，变成单独可执行参数，也就是改成：PaddleOCR_json.exe 支持的CLI命令格式有三个参数 -use_debug、-image_dir、-use_system_pause

**Comment by hiroi-sora** [comment]
在我原本的设定中，ensure_ascii、use_system_pause、ensure_chcp是单独生效的参数，并不是use_debug的子参数，本身就是可以单独调整的。
看了你的描述后我再检查了代码，发现这是我的疏忽，use_debug=true（即默认值）时会强制覆盖 ensure_ascii、use_system_pause、ensure_chcp 三个参数。这个bug之后会修改。

目前，要实现你的目的，可以关闭debug模式，然后手动指定不转义ASCII。如下：
`PaddleOCR_json.exe -image_dir="D:\t1.png" -use_debug=0 -ensure_ascii=0`
