### ISSUE TITLE
建议更新维护一下README.md

### ISSUE THREAD

**Issue by sls463** [hiroi-sora/PaddleOCR-json#39]
在“返回值说明”下添加以下内容 (也许我写得不太对，你看着修改^_^)

300	JSON转储失败了. 编码错误
data为字符串：JSON dump failed. Coding error.
原因：命令行调用方式采用了 方式1：启动参数，通过-image_dir参数传入的图片路径中包含有中文，需修改成不含中文的路径才行

**Comment by hiroi-sora** [comment]
哦哦，感谢指出，确实是漏了一条。

**Comment by sls463** [comment]
图片路经为 D:\CP协议.png ，用命令行调用返回300, 我就去查故障码说明，结果没找到300，最大只有299,  后来改成 D:\CP.png 再试，就正常OCR了，所以我推测是路经中含有中文才返回300

**Comment by hiroi-sora** [comment]
OK感谢，已确认问题。通过启动参数传入非法编码路径时报错300其实是常见现象。
