### ISSUE TITLE
请问可以让封装的exe文件直接返回JSON字符串吗？

### ISSUE THREAD

**Issue by nightson** [hiroi-sora/PaddleOCR-json#4]
非Python开发者，纯业余小白，为了解决日常办公需求写了个Powershell脚本，如果运行"PaddleOCR_json.exe 图片路径"能够直接返回JSON结果比较方便调用。不知道能不能满足鄙人的这个需求，万分感谢！

**Comment by hiroi-sora** [comment]
不采用启动参数传递的方式是特意设计的，为了避免重复初始化加载模型库的开销。

我写了个Powershell调用PaddleOCR_json的[demo](https://github.com/hiroi-sora/PaddleOCR-json#powershell%E8%B0%83%E7%94%A8)，或许你可以参考一下。不过我对Powershell不是很熟，还有一些编码转换之类的问题未能解决，抱歉。

**Comment by AutumnSun1996** [comment]
感觉可以实现成一个常驻的后台进程, 通过HTTP接口(或者自定义的TCP协议)来交互. 不过工作量就比较大了.
用JSON的话, 可以通过JSON的ascii编码避免GBK/UTF8的问题吧, 不过不太清楚作者使用的json库的具体实现.

**Comment by hiroi-sora** [comment]
> 通过ascii编码避免GBK/UTF8的问题
@AutumnSun1996 
感谢，很有用的提议。有空了会尝试添加这个功能

**Comment by hiroi-sora** [comment]
实用化的 PowerShell API 已更新，只需几行代码就可以调用OCR了
