### ISSUE TITLE
如果编译GPU版本能兼容吗

### ISSUE THREAD

**Issue by pak12315** [hiroi-sora/PaddleOCR-json#40]

**Comment by hiroi-sora** [comment]
应该可以，本项目的代码与CPU/GPU版本无关。
不过建议按照[传统构建](https://github.com/hiroi-sora/PaddleOCR-json/blob/main_old_builds/docs/%E9%A1%B9%E7%9B%AE%E6%9E%84%E5%BB%BA%E6%8C%87%E5%8D%97.md)方式，调通PPOCR的GPU版本demo，再替换入本项目的c++代码。

**Comment by pak12315** [comment]
感谢~！
