### ISSUE TITLE
行错位等

### ISSUE THREAD

**Issue by LingFanDeLe** [hiroi-sora/PaddleOCR-json#41]
您好，感谢，汇报下
1、顺时针90°图片读完，行错位了
2、请问Win Server 2012不能直接运行是吗？

**Comment by hiroi-sora** [comment]
> 如何处理90/270°翻转的图片？

如果你是用Python调用，建议使用本项目附带的Python API，其中有 [文本后处理模块](https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python#%E6%96%87%E6%9C%AC%E5%90%8E%E5%A4%84%E7%90%86-tbpu) 专门用于按顺序整理和合并每行的文本块。可以使用 `竖排-从右至左-单行` 模式来实现你的需求。

如果你是其它语言调用，可以参考以上Python API的代码，自己写一个文本顺序整理的功能。

> Win Server 2012

这是基于win8的，本项目目前只支持在win10及以上的系统运行，抱歉。未来会开发更多系统兼容。

**Comment by LingFanDeLe** [comment]
辛苦了
