### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by ye13533167453** [hiroi-sora/PaddleOCR-json#43]
![89a86003018bff586f79faccffb9b7b](https://user-images.githubusercontent.com/7224845/230515637-17ab21ae-f884-4973-b665-41449dbdbe70.png)
python调用启动时，仅初始化只有100M左右，正常。
当ocr方法调用多次时，paddleOCR-json.exe进程的内存逐步飙到七百多M，而且，你停止调用ocr，内存并不会释放

**Comment by ye13533167453** [comment]
而且，我尝试调用ocr方法的过程，改成单进程单线程，以此来避免并发的干扰，测试结果也是内存占用非常大，无法释放

**Comment by hiroi-sora** [comment]
这是PaddleOCR C++引擎的一个“特性”，内存占用非常激进。但是占用率不会无限制的上升，达到一定值后会放缓直至停止。一般不会因此导致崩溃的问题。

![image](https://user-images.githubusercontent.com/56373419/233836432-afcaa0a7-a6d9-4f60-8c2b-5caa0983d592.png)

上图是我以前做的测试，内存主要是给mkldnn库吃了。这个库我改不了所以也无法确定是它的哪里出了问题。如果你想降低内存占用，则将引擎的mkldnn关了即可，传入 `--enable_mkldnn=0` 。注意这会降低识别速度。

或者，你可以参考我的 [Umi-OCR v1.3.3](https://github.com/hiroi-sora/Umi-OCR/tree/main/ocr) ，用手动重启引擎的方式来释放当前的内存占用。如果选择恰当的时机（如任务的空隙）重启，则对识别速度的影响较小。

**Comment by ye13533167453** [comment]
非常感谢大神的解答，最近忙上线少，回复晚了，我用重启的形式来处理，曲线救国了

**Comment by Aaron2im** [comment]
@hiroi-sora 你好，请问docker部署该怎么设置这个参数呢？
