### ISSUE TITLE
传统方法构建失败

### ISSUE THREAD

**Issue by kenaky** [hiroi-sora/PaddleOCR-json#45]
按照“方式1. 传统构建”方法构建，已经按照PaddleOCR官方“Visual Studio 2019 Community CMake 编译指南”成功编译得到了ppocr.exe，并将项目的project_files\cpp_infer下include和src两个目录中的文件替换到了官方工程相同路径中，再次打开sln项目文件重新build，报了一堆错误，例如：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E1696	无法打开 源 文件 "nlohmann/json.hpp"
错误(活动)	E0725	名称必须是命名空间名
错误(活动)	E0020	未定义标识符 "json"
错误(活动)	E0020	未定义标识符 "json"
错误(活动)	E0020	未定义标识符 "json"
错误(活动)	E0020	未定义标识符 "json"
错误(活动)	E0276	后面有“::”的名称一定是类名或命名空间名
错误(活动)	E0020	未定义标识符 "json"	
错误	C2062	意外的类型“int”
错误	C2059	语法错误:“{”
错误	C2334	“{”的前面有意外标记；跳过明显的函数体
错误	C2530	“PaddleOCR::Classifier::gpu_id”: 必须初始化引用
......
看了一下，感觉是缺少了一些头文件所导致。对比了项目project_files和官方工程生成的的CMakeLists文件，确实不太一样，项目project_files\cpp_infer下src中的CMakeLists文件多了很多依赖的package。
所以，简单的将include和src两个目录中的文件替换到了官方工程相同路径，是否不可行？是否还漏了其他步骤？还是说文件合并后，还需要重新用cmake构建一次项目？

**Comment by hiroi-sora** [comment]
这个问题是由于用错了分支。

![image](https://user-images.githubusercontent.com/56373419/231670561-148620a5-3f0a-4981-be62-fa5ef7835be7.png)
![image](https://user-images.githubusercontent.com/56373419/231670814-6776c23c-5740-4bc9-a9ec-93f73fc97181.png)


nlohmann-json是一个第三方库。在传统构建构建（main_old_builds分支）中，`nlohmann/json.hpp`直接嵌入本项目的源代码中。而在新构建（main分支）中，这个库由vcpkg管理，因此不包含在本项目文件中。

因此，当你使用传统构建+main分支，会出现找不到`nlohmann/json.hpp`的错误。
请下载[main_old_builds分支](https://github.com/hiroi-sora/PaddleOCR-json/tree/main_old_builds)的代码，重新替换到project_files\cpp_infer中。（理论上只需替换代码文件即可，不需要重新走一遍前面的流程。）

**Comment by kenaky** [comment]
原来如此，怪不得了~多谢指正。
