### ISSUE TITLE
参数说明是不是写错误了

### ISSUE THREAD

**Issue by xxdoc** [hiroi-sora/PaddleOCR-json#49]
<html>
<body>

键名称 | 默认值 | 值说明
-- | -- | --
addr | -1 | 指定开展服务的端口。传入0时随机端口，传入1~65535则设为该端口。
port | loopback | 可选值：loopback仅在本地环回（127.0.0.1）开展服务。any在本机任何可用ip地址开展服务。

</body>
</html>

**Comment by hiroi-sora** [comment]
嗯，手滑写反了，感谢指正。已更改。

**Comment by zzj450591538** [comment]
我怎么感觉  port 还是本地本地环回
