### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by imohuan** [hiroi-sora/PaddleOCR-json#5]
你好，我想请问一下作者使用的什么软件打包的？

我目前想打包一个深度学习的Python代码lama，可是一直打包不成功
我是使用了nuitka和pyinstaller，可惜都没有成功，使用nuitka打包了1个多小时，内存积累到了将近10g，导致最后内存不足失败
我正常跑是可以的，但是不能打包出来
这是我的打包命令
`nuitka --standalone --show-memory --mingw64 --show-progress --windows-icon-from-ico=./favicon.ico --output-dir=out ./bin/predict.py`

所以我想请教一下作者是如何打包PaddleOcr的？
我的目标是将python库打包成一个命令行功能工具

**Comment by imohuan** [comment]
我使用 `nuitka` 打包 PaddleOcr 的时候后面报错 `AssertionError: tools.`

**Comment by hiroi-sora** [comment]
你好，我很乐意分享一下经验。

首先，这个项目并不是Python写的，而是基于 [PPOCR C++版引擎](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/docs/windows_vs2019_build.md) 。我选用C++版的原因之一是因为性能（比Python版快2~5倍），原因之二就是打包问题。

Paddle这类大型Python库有很多外部资源或依赖（模型，字典，dll运行库等）。这带来了几个潜在的隐患：
1. pip安装（或者第一次运行）时要下载大量的额外资源，比如某些小语种的库，可能你永远也用不到它。而用pyinstaller等工具打包，常常把资源文件、或无关的库照单全收，导致打出来的包体积巨大，直逼1g。
2. 打包工具可能找不到某个资源或依赖，打包失败。
3. 打包成功，但某些依赖（尤其是模型、dll链接库）没有被包含到exe里，导致无法运行（或拷贝到别的机器上无法运行）。

所以，如果你一定要使用Python版PaddleOCR并想打包为exe，我的建议是：
1. 理清你项目里具体用了那些资源或依赖，库文件里不必要的资源可以尝试删去
2. 使用虚拟环境打包，避免无关的库被收入
3. 手写打包参数配置文件 `**.spec` ，将有用到的库写进去
4. 模型库字典等资源文件及vcruntime、opencv等dll链接库，可以选择一并打包进exe，或放在外部同目录下（代码中可能要设置以相对路径导入）
5. 打包失败或运行时出现 Error: Can not import xxx / 缺失xxx模块 之类的提示，按着提示的路径去找遗漏的资源，重新打包或拷贝到外部目录下
6. [尝试QPT](https://github.com/PaddlePaddle/PaddleOCR/issues/5929#issuecomment-1094765629)

**Comment by imohuan** [comment]
非常感谢你的建议
