### ISSUE TITLE
socket在本机测试OK，在不同机器上则出现接收数据不完整

### ISSUE THREAD

**Issue by lisp2021** [hiroi-sora/PaddleOCR-json#51]
windows作为socket server ，python和golang的客户端连接socket可以连上但是服务端报错接收数据大小不足导致json解析失败

**Comment by hiroi-sora** [comment]
感谢反馈。问题已修复，并发布到 [alpha.2](https://github.com/hiroi-sora/PaddleOCR-json/releases/tag/v1.3.0_alpha.1)

**Comment by lisp2021** [comment]
tks
