### ISSUE TITLE
c++调用接口

### ISSUE THREAD

**Issue by panda-o-o** [hiroi-sora/PaddleOCR-json#59]
作者您好，就是我算一个新手，想知道的就是可不可以在另外一个项目中直接使用c++调用exe文件，然后返回json到另外一个项目

**Comment by hiroi-sora** [comment]
第三方c++项目调用exe当然可以，但是感觉有点脱裤子放屁😂因为这个引擎本身是c++写的，你可以将引擎代码嵌入你的项目，或者在引擎代码的基础上拓展你的项目。避免了exe进程交互，效率更高。

**Comment by panda-o-o** [comment]
好的，大佬，我来试试将引擎代码嵌入我的项目来试试，还是非常非常感谢
