### ISSUE TITLE
编译动态dll问题

### ISSUE THREAD

**Issue by whuhit** [hiroi-sora/PaddleOCR-json#6]
你好，我按照你的教程编译成一个exe，然后通过python可以调用执行。但是我编译成一个动态dll，再通过python调用的时候就一直报错。报错信息如下：

> PreconditionNotMetError: The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly. (error code is 182)

不知道你试过编译dll么，会不会遇到同样的错误。

**Comment by hiroi-sora** [comment]
1. 有将`mklml.dll`放在OCR程序同一目录下么？
2. python调用时有没有设置正确的工作路径（程序所在的目录）？

> 不知道你试过编译dll么

我觉得dll坑比较多。弄成exe作为一个完全独立的组件来调用，比较舒服，方便排查问题。

**Comment by whuhit** [comment]
目录设置都是没问题的，和编译exe一样的路径。编译dll，我之前想的是可以把模型初始化和识别弄成两个接口，这样初始化可以只调用一次。但是你这个exe好像也解决了这个问题，挺好的👍发自我的iPhone------------------ 原始邮件 ------------------发件人: hiroi-sora  ***@***.***>发送时间: 2022年9月9日 18:19收件人: hiroi-sora/PaddleOCR-json ***@***.***>抄送: whuhit ***@***.***>, Author ***@***.***>主题: Re: [hiroi-sora/PaddleOCR-json] 编译动态dll问题 (Issue #6)

有将mklml.dll放在OCR程序同一目录下么？
python调用时有没有设置正确的工作路径（程序所在的目录）？


不知道你试过编译dll么

我觉得dll坑比较多。弄成exe作为一个完全独立的组件来调用，比较舒服，方便排查问题。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/hiroi-sora/PaddleOCR-json/issues/6#issuecomment-1241786552",
"url": "https://github.com/hiroi-sora/PaddleOCR-json/issues/6#issuecomment-1241786552",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
