### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by LiLovewei** [hiroi-sora/PaddleOCR-json#62]
支持把项目部署在win 7上吗

**Comment by hiroi-sora** [comment]
一些科学计算库存在兼容性问题，所以不支持win8及以下的系统。

如果有必要使用win7，可尝试隔壁 [RapidOCR-json](https://github.com/hiroi-sora/RapidOCR-json)

**Comment by hiroi-sora** [comment]
现在已经支持win7了。
