### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by LiLovewei** [hiroi-sora/PaddleOCR-json#63]
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/20395838/0d6fbc62-2b24-4b1d-b286-3b42b2ab7ae5)

cmake 按步骤下来报错
CMake Error in CMakeLists.txt:
  OUTPUT containing a "#" is not allowed.
然后我把 cpp下的CMakeLists.txt 里面的# Note: libpaddle_inference_api.so/a must put before libpaddle_inference.so/a 删除后，依然提示这个错误。vs版本和opencv版本和文章中的一样，cmake版本为3.27.0-rc4

**Comment by hiroi-sora** [comment]
首先， CMakeLists.txt 中的#是注释，不是引起这个报错的原因。

然后，请检查`项目路径`、`.source的路径`、`cmake安装路径`、`windows用户名（我的文档路径）` 中是否含有#号或别的特殊字符（包括中文）。如果有，尝试删去。

建议先清除之前留下的文件和痕迹，从头开始执行一次构建步骤。如果还有相同的问题，给请给一张完整的cmake gui界面截图，我们再想想办法。
