### ISSUE TITLE
nodejs,调用初始化失败

### ISSUE THREAD

**Issue by lihaopeng1024** [hiroi-sora/PaddleOCR-json#65]
(node:1920) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron --trace-deprecation ...` to show where the warning was created)
error Error: spawn PaddleOCR_json.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ENOENT',
  syscall: 'spawn PaddleOCR_json.exe',
  spawnargs: [ '-config_path="models\\config_chinese.txt"', '--use_debug=0' ]
}

**Comment by lihaopeng1024** [comment]
已解决，是我代码编写的问题

**Comment by PunchlY** [comment]
`ENOENT` 码表示为未查询到目录或文件, 请输入正确的 `path` 与 `options.cwd`.
此问题已解决, 建议关闭.

**Comment by leiSaint** [comment]
> 已解决，是我代码编写的问题

你好，能请教一下怎么调用的吗？我使用spawn调用时，只能输出一行PaddleOCR-json v1.3.0，其他的都无法输出。我用python调用，也是只能输出一行PaddleOCR-json v1.3.0，然后提示两个模型库找不到。想请教一下你是怎么解决的。谢谢。
