### ISSUE TITLE
【致谢,被其他开源项目用到了】QT+Rust开发的paddleOCR桌面软件（示例）

### ISSUE THREAD

**Issue by kerneltravel** [hiroi-sora/PaddleOCR-json#74]
[这个项目](https://github.com/kerneltravel/rust_qt_gui_paddle_ocr_example) 用到了 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) ，主要演示了Rust+QT 开发 OCR 桌面软件的可行性。

**Comment by hiroi-sora** [comment]
感谢！

那么能否将调用接口部分分离出来，贡献到本项目呢？可参考 [提供新API](https://github.com/hiroi-sora/PaddleOCR-json/blob/main/docs/%E8%AF%A6%E7%BB%86%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.md#%E6%8F%90%E4%BE%9B%E6%96%B0api) 。

**Comment by kerneltravel** [comment]
Rust 的调用接口部分，已经是独立的了，是其他人开源的rust的crate仓库： https://lib.rs/crates/paddleocr  。github地址： https://github.com/overflowcat/paddleocr
