### ISSUE TITLE
MingW64 编译的C++项目，是不是不能嵌入本项目？

### ISSUE THREAD

**Issue by xkungxfu** [hiroi-sora/PaddleOCR-json#79]
我注意到本项目是[Visual Studio 2019]编译的。
我的项目是用的qt creator，mingw编译的。

**Comment by hiroi-sora** [comment]
编译器应该不会影响。引擎最核心的推理库已经是预编译了的，本项目中的c++代码不涉及引擎底层运算，理论上兼容性较好。

其次，本项目的主旨是作为一个中转站，让非c++语言 能方便的调用c++推理引擎。如果你调用方本身就是c++项目，那么其实不需要本项目作为中转站；直接使用 [PaddleOCR官方的c++代码](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/deploy/cpp_infer/readme_ch.md) 或许更好。

**Comment by xkungxfu** [comment]
编译本项目 提示：
ninja: error: '/paddle/lib/paddle_inference.a', needed by 'ppocr.exe', missing and no known rule to make it
看上去需要先编译官方原版的ppocr

看了一下原版的文档，要编译没那么容易。我还是放弃了。就用你的EXE好了。

谢谢。
