### ISSUE TITLE
ocr.runBase64(base64Str)运行后无法获取正确结果

### ISSUE THREAD

**Issue by lvshunbin** [hiroi-sora/PaddleOCR-json#81]
![1697026902355](https://github.com/hiroi-sora/PaddleOCR-json/assets/41767662/e23d4e10-2b8d-4734-becb-894d1e9e6748)
获取到的结果为：
{'code': 200, 'data': 'Image path dose not exist. Path: ""', 'hotUpdate': '. '}

**Comment by hiroi-sora** [comment]
你的 `PaddleOCR-json.exe` 是老版本，还不支持Base64识图。（因为老版本的返回值才有hotUpdate，新版本已经取消了热更新机制。）

去Release下载个新版本exe即可。

**Comment by lvshunbin** [comment]
谢谢，按照您的提示已经可以了 @hiroi-sora
