### ISSUE TITLE
无法使用PIL读取的图片进行识别，也无法使用字节流

### ISSUE THREAD

**Issue by youde2000** [hiroi-sora/PaddleOCR-json#84]
这是你的demo代码
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/54662806/15c043c2-3d37-410e-aa04-71b11be2f3e5)
这是我的本地输出结果
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/54662806/6d48841c-8b8a-41a6-8ab1-4fb3df34cd68)
我使用的是最新的工具
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/54662806/7fe15ea2-a88a-4bde-a486-06537a9a27c4)

**Comment by hiroi-sora** [comment]
关于问题1：
请在PPOCR_api.py 第60行 插入如下语句，检查一下输入指令是否正确：
```python
        print("检查：", writeDict.keys())
```
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/56373419/0f3fb3f9-f957-41f8-9440-51a92101b8a9)


关于问题2：可能是你的测试图片含alpha通道导致PIL转换失败。demo1中使用如下代码即可：
```python
pilImage = Image.open(TestImagePath)
pilImage = pilImage.convert("RGB")  # 添加这行代码，将图像转换为 RGB 模式
buffered = BytesIO()
pilImage.save(buffered, format="JPEG")
```
