### ISSUE TITLE
无法使用ch_PP-OCRv4_rec_infer

### ISSUE THREAD

**Issue by youde2000** [hiroi-sora/PaddleOCR-json#85]
你好，目前最新的识别模型是ch_PP-OCRv4_rec_infer，但是这个工具似乎不能使用ch_PP-OCRv4_rec_infer进行识别，我将识别模型换成v4的，结果识别出来的是乱码。
![Uploading img.png…]()

**Comment by hiroi-sora** [comment]
是的，Paddle发布v4后，并没有更新以往的c++ mkl推理库，因此旧推理库对v4模型存在兼容性问题。
Paddle另外搞了一套fast deploy的新推理框架，本项目可能会在以后更新到该框架。

目前，你可以在RapidOCR中体验v4模型。此项目的Release包中已经默认附带了v4模型。
https://github.com/hiroi-sora/RapidOCR-json

**Comment by ASC8384** [comment]
> 是的，Paddle发布v4后，并没有更新以往的c++ mkl推理库，因此旧推理库对v4模型存在兼容性问题。 Paddle另外搞了一套称为fast deploy的新推理框架，本项目可能会在以后更新到该框架。
> 
> 目前，你可以在RapidOCR中体验v4模型。此项目的Release包中已经默认附带了v4模型。 https://github.com/hiroi-sora/RapidOCR-json

您好，请问最近有更新计划吗？

**Comment by hiroi-sora** [comment]
抱歉，暂时没有专门为 “兼容v4模型库” 而设计的更新计划，因为感觉收益不大（v4的实际体验并没有质变）。

未来更新表格识别/版面分析功能时，才会一并把v4兼容的问题解决。

至于时间，应该也不会在“近期”，因为比较忙😂
