### ISSUE TITLE
推理结果问题

### ISSUE THREAD

**Issue by BrownTen** [hiroi-sora/PaddleOCR-json#86]
作者你好。

- 我按照PaddlePaddle/PaddleOCR的[Python快速开始](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/quickstart.md)，采用2.6release，PPOCR-v3模型对下方图片内容进行识别，有两行内容无法识别出来，如图所示
- 但是采用作者你构建的PaddleOCR-json.exe同样使用 Python API 对该图片进行识别，能很好的全部识别出来

我想着两个方案使用的模型都是一样的，结果也应该是一样，可事实却有偏差。
请问作者是在构建的时候做了其他的参数调整吗？还是存在其他的问题。

望作者能够拨冗回复，感谢！
![PPOCR-v3识别结果](https://github.com/hiroi-sora/PaddleOCR-json/assets/49226327/b3d9f3a6-73a8-45fa-8eb4-872e33f98359)

**Comment by hiroi-sora** [comment]
你可以参考本项目的参数文件：
https://github.com/hiroi-sora/PaddleOCR-json/blob/main/cpp/src/args.cpp

检查其中的参数设置，是否与你Python代码设定的一致。

**Comment by hiroi-sora** [comment]
c++和python的推理库可能在输入数据预处理、模型库加载等阶段使用不同的方式，得出的结果不同是很正常的。就算只是c++，paddle有多组不同的c++推理后端，输出也可能有细微区别。

甚至同一个推理模块在CPU或GPU上执行，得出的结果都可能不同。

当然，这些误差不会很大。关于你的例子，直接丢失了两段清晰文本，我觉得不属于误差，是比较明显的性能问题。

你可以检查一下det部分，看看只用det有没有捕获到这两段文本的框框。

**Comment by BrownTen** [comment]
> 你可以参考本项目的参数文件： https://github.com/hiroi-sora/PaddleOCR-json/blob/main/cpp/src/args.cpp
> 
> 检查其中的参数设置，是否与你Python代码设定的一致。

感谢，我已经完成了参数的匹配和筛选，目前做下来的结果是，use_angle_cls 方向分类器 和 det_db_score_mode 多边形框计算 对结果的影响较大。

**Comment by hiroi-sora** [comment]
use_angle_cls 一般不用开，除非文字旋转了90 / 180° 。对于正常方向的文字，cls对结果无影响的。
