### ISSUE TITLE
使用python-api的依赖包

### ISSUE THREAD

**Issue by leo1515416043** [hiroi-sora/PaddleOCR-json#88]
期望在python项目里内嵌此引擎。ReadMe介绍Python API部分：`from PPOCR_api import GetOcrApi`。
使用PPOCR_api需要安装什么package？

**Comment by hiroi-sora** [comment]
将 [这个目录下的文件](https://github.com/hiroi-sora/PaddleOCR-json/tree/main/api/python) 放到你的项目中。或者只需要放置 `PPOCR_api.py` 单文件即可。
