### ISSUE TITLE
python调用，存在内存泄漏，跑了一天，内存增长到6G

### ISSUE THREAD

**Issue by chencanhero** [hiroi-sora/PaddleOCR-json#90]

**Comment by hiroi-sora** [comment]
这是mkldnn加速库的祖传问题。解决方法有：

1. 传入`--enable_mkldnn=0`禁用mkl。但是OCR速度会受到较大影响。
2. 每隔一段时间，比如60s内没有新的任务，就重启一次引擎。这也是Umi-OCR的做法。
3. 使用隔壁RapidOCR-json
