### ISSUE TITLE
能否识别PDF文件呢？

### ISSUE THREAD

**Issue by chengyuyu** [hiroi-sora/PaddleOCR-json#92]
原版的PaddleOCR可以识别PDF文件，能否增加对pdf文件的图片内容的识别呢？

**Comment by hiroi-sora** [comment]
[Umi-OCR](https://github.com/hiroi-sora/Umi-OCR) 正在开发PDF识别功能。PDF解析部分将由Umi本身 而不是PaddleOCR引擎负责。PaddleOCR-json 暂时没有更新计划。

**Comment by yangyunlv** [comment]
为啥我用Umi-OCR打印识别结果的时候比这里多出了两个'from': 'text', 'end': ''，是这边的版本还没更新吗

**Comment by hiroi-sora** [comment]
> 是这边的版本还没更新吗

PDF解析部分由Umi-OCR中的组件负责。这边 PaddleOCR-json 是单纯的OCR引擎，没有PDF解析功能。

"from" 和 "end" 也是 Umi 的解析结果，与 Paddle 无关。
