### ISSUE TITLE
下载c++源码，编译的时候出现非常多错误

### ISSUE THREAD

**Issue by qiaonanxiansheng** [hiroi-sora/PaddleOCR-json#99]
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/162696111/6128510e-fdbc-4fd9-8fa4-7051b0112917)

**Comment by qiaonanxiansheng** [comment]
我检查了好几遍，之前的步骤应该是没什么问题的

**Comment by hiroi-sora** [comment]
这一步you有没有做

![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/56373419/6c926ef9-a70f-41ef-b15c-b5f96f66b24b)

**Comment by qiaonanxiansheng** [comment]
做了啊，报的错莫名其妙，比如
![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/162696111/cb3583b9-53e5-4b22-99b4-a5204c23f131)

**Comment by qiaonanxiansheng** [comment]
我本人是java和python的，对c++不熟悉，希望大哥多多指定。

**Comment by hiroi-sora** [comment]
我在虚拟机里完整地重试了一次构建。严格按照文档说明操作的话，是没有问题的。

系统：win10
VS 2019
依赖库按文档中的链接下载最新版即可

![image](https://github.com/hiroi-sora/PaddleOCR-json/assets/56373419/b19d0ea1-dd7c-42cf-96bf-1fa722db7c62)

还是你的某一步操作出了问题，但是已知信息太少，我也无法判断。

不过可以提醒你：VS一长串报错，只有一两个是关键的。那些提示语法错误的都可以不管，找到最关键的报错，搜一下解决方法，有概率能知道问题出在哪。

**Comment by hiroi-sora** [comment]
也有一定可能是编码问题，你从github下载的源代码的编码有一些转换，导致VS无法识别某些行的换行符。

可参考 [这里](https://blog.csdn.net/weixin_39252106/article/details/120370045) ，将所有源码文件的换行符转为 CR LF

**Comment by qiaonanxiansheng** [comment]
@hiroi-sora 感谢指点。我这里需要把所有的.cp和include下面的.h文件，的换行符格式改为pc版才能通过编译。谢谢
